package it.avlp.simog.massload.xmlbeans;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-03T09:18:46.370+02:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "LoaderAppaltoWSService",
                  wsdlLocation = "file:/C:/gitworkspaces/sitat-maggioli/consulta-simog-2/src/main/resources/wsdl/LoaderAppaltoWS.wsdl",
                  targetNamespace = "xmlbeans.massload.simog.avlp.it")
public class LoaderAppaltoWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("xmlbeans.massload.simog.avlp.it", "LoaderAppaltoWSService");
    public final static QName LoaderAppaltoWSPort = new QName("xmlbeans.massload.simog.avlp.it", "LoaderAppaltoWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/gitworkspaces/sitat-maggioli/consulta-simog-2/src/main/resources/wsdl/LoaderAppaltoWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoaderAppaltoWSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/gitworkspaces/sitat-maggioli/consulta-simog-2/src/main/resources/wsdl/LoaderAppaltoWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoaderAppaltoWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoaderAppaltoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoaderAppaltoWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LoaderAppaltoWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LoaderAppaltoWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LoaderAppaltoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LoaderAppaltoWS
     */
    @WebEndpoint(name = "LoaderAppaltoWSPort")
    public LoaderAppaltoWS getLoaderAppaltoWSPort() {
        return super.getPort(LoaderAppaltoWSPort, LoaderAppaltoWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoaderAppaltoWS
     */
    @WebEndpoint(name = "LoaderAppaltoWSPort")
    public LoaderAppaltoWS getLoaderAppaltoWSPort(WebServiceFeature... features) {
        return super.getPort(LoaderAppaltoWSPort, LoaderAppaltoWS.class, features);
    }

}
