package it.avlp.simog.massload.xmlbeans;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-11-24T14:04:04.414+01:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "SimogWSPDDService",
                  wsdlLocation = "classpath:wsdl/SimogWSPDD.wsdl",
                  targetNamespace = "xmlbeans.massload.simog.avlp.it")
public class SimogWSPDDService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("xmlbeans.massload.simog.avlp.it", "SimogWSPDDService");
    public final static QName SimogWSPDDPort = new QName("xmlbeans.massload.simog.avlp.it", "SimogWSPDDPort");
    static {
        URL url = SimogWSPDDService.class.getClassLoader().getResource("wsdl/SimogWSPDD.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SimogWSPDDService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/SimogWSPDD.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SimogWSPDDService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SimogWSPDDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimogWSPDDService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SimogWSPDDService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SimogWSPDDService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SimogWSPDDService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SimogWSPDD
     */
    @WebEndpoint(name = "SimogWSPDDPort")
    public SimogWSPDD getSimogWSPDDPort() {
        return super.getPort(SimogWSPDDPort, SimogWSPDD.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimogWSPDD
     */
    @WebEndpoint(name = "SimogWSPDDPort")
    public SimogWSPDD getSimogWSPDDPort(WebServiceFeature... features) {
        return super.getPort(SimogWSPDDPort, SimogWSPDD.class, features);
    }

}
