package it.appaltiecontratti.monitoraggiocontratti.contratti.entity.entries;

import it.appaltiecontratti.sicurezza.annotations.XSSValidation;

public class DelegaEntry {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.w9deleghe.id
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.w9deleghe.codrup
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	@XSSValidation
	private String cfrup;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.w9deleghe.codtec
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	@XSSValidation
	private String codtec;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.w9deleghe.id_collaboratore
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	private Long idCollaboratore;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.w9deleghe.ruolo
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	private Short ruolo;
	
	private String nomeCollaboratore;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.w9deleghe.id
	 *
	 * @return the value of public.w9deleghe.id
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.w9deleghe.id
	 *
	 * @param id the value for public.w9deleghe.id
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	



	public String getCfrup() {
		return cfrup;
	}

	public void setCfrup(String cfrup) {
		this.cfrup = cfrup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.w9deleghe.codtec
	 *
	 * @return the value of public.w9deleghe.codtec
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	public String getCodtec() {
		return codtec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.w9deleghe.codtec
	 *
	 * @param codtec the value for public.w9deleghe.codtec
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	public void setCodtec(String codtec) {
		this.codtec = codtec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.w9deleghe.id_collaboratore
	 *
	 * @return the value of public.w9deleghe.id_collaboratore
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	public Long getIdCollaboratore() {
		return idCollaboratore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.w9deleghe.id_collaboratore
	 *
	 * @param idCollaboratore the value for public.w9deleghe.id_collaboratore
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	public void setIdCollaboratore(Long idCollaboratore) {
		this.idCollaboratore = idCollaboratore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.w9deleghe.ruolo
	 *
	 * @return the value of public.w9deleghe.ruolo
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	public Short getRuolo() {
		return ruolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.w9deleghe.ruolo
	 *
	 * @param ruolo the value for public.w9deleghe.ruolo
	 *
	 * @mbg.generated Wed Mar 23 17:13:40 ICT 2022
	 */
	public void setRuolo(Short ruolo) {
		this.ruolo = ruolo;
	}

	public String getNomeCollaboratore() {
		return nomeCollaboratore;
	}

	public void setNomeCollaboratore(String nomeCollaboratore) {
		this.nomeCollaboratore = nomeCollaboratore;
	}


}