package it.appaltiecontratti.monitoraggiocontratti.contratti.entity.entries;

public class W9loaderAppaltoUsr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.w9loader_appalto_usr.syscon
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	private Long syscon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.w9loader_appalto_usr.simoguser
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	private String simoguser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.w9loader_appalto_usr.simogpass
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	private String simogpass;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.w9loader_appalto_usr.syscon
	 * @return  the value of public.w9loader_appalto_usr.syscon
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	public Long getSyscon() {
		return syscon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.w9loader_appalto_usr.syscon
	 * @param syscon  the value for public.w9loader_appalto_usr.syscon
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	public void setSyscon(Long syscon) {
		this.syscon = syscon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.w9loader_appalto_usr.simoguser
	 * @return  the value of public.w9loader_appalto_usr.simoguser
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	public String getSimoguser() {
		return simoguser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.w9loader_appalto_usr.simoguser
	 * @param simoguser  the value for public.w9loader_appalto_usr.simoguser
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	public void setSimoguser(String simoguser) {
		this.simoguser = simoguser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.w9loader_appalto_usr.simogpass
	 * @return  the value of public.w9loader_appalto_usr.simogpass
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	public String getSimogpass() {
		return simogpass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.w9loader_appalto_usr.simogpass
	 * @param simogpass  the value for public.w9loader_appalto_usr.simogpass
	 * @mbg.generated  Thu Apr 28 09:58:06 ICT 2022
	 */
	public void setSimogpass(String simogpass) {
		this.simogpass = simogpass;
	}
}