/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.AppaltoP3BaseType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.DatiBaseAppaltoType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.DatiBaseStrumentiProceduraSistemaDinamicoAstaType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.StrumentiSvolgimentoProcedureEnum;
import java.util.UUID;
/**
 * Oggetto che riporta i dati dell&#x27;appalto.
 */
@Schema(description = "Oggetto che riporta i dati dell'appalto.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:13:15.678079400+02:00[Europe/Berlin]")

public class AppaltoP33Type extends AppaltoP3BaseType {
  @JsonProperty("cigAccordoQuadroConvenzione")
  private String cigAccordoQuadroConvenzione = null;

  @JsonProperty("datiBase")
  private DatiBaseAppaltoType datiBase = null;

  @JsonProperty("datiBaseProcedura")
  private AllOfAppaltoP33TypeDatiBaseProcedura datiBaseProcedura = null;

  @JsonProperty("datiBaseStrumentiProcedura")
  private DatiBaseStrumentiProceduraSistemaDinamicoAstaType datiBaseStrumentiProcedura = null;

  public AppaltoP33Type cigAccordoQuadroConvenzione(String cigAccordoQuadroConvenzione) {
    this.cigAccordoQuadroConvenzione = cigAccordoQuadroConvenzione;
    return this;
  }

   /**
   * CIG relativo all’accordo quadro/convenzione cui si aderisce
   * @return cigAccordoQuadroConvenzione
  **/
  @Schema(required = true, description = "CIG relativo all’accordo quadro/convenzione cui si aderisce")
  public String getCigAccordoQuadroConvenzione() {
    return cigAccordoQuadroConvenzione;
  }

  public void setCigAccordoQuadroConvenzione(String cigAccordoQuadroConvenzione) {
    this.cigAccordoQuadroConvenzione = cigAccordoQuadroConvenzione;
  }

  public AppaltoP33Type datiBase(DatiBaseAppaltoType datiBase) {
    this.datiBase = datiBase;
    return this;
  }

   /**
   * Get datiBase
   * @return datiBase
  **/
  @Schema(required = true, description = "")
  public DatiBaseAppaltoType getDatiBase() {
    return datiBase;
  }

  public void setDatiBase(DatiBaseAppaltoType datiBase) {
    this.datiBase = datiBase;
  }

  public AppaltoP33Type datiBaseProcedura(AllOfAppaltoP33TypeDatiBaseProcedura datiBaseProcedura) {
    this.datiBaseProcedura = datiBaseProcedura;
    return this;
  }

   /**
   * Get datiBaseProcedura
   * @return datiBaseProcedura
  **/
  @Schema(required = true, description = "")
  public AllOfAppaltoP33TypeDatiBaseProcedura getDatiBaseProcedura() {
    return datiBaseProcedura;
  }

  public void setDatiBaseProcedura(AllOfAppaltoP33TypeDatiBaseProcedura datiBaseProcedura) {
    this.datiBaseProcedura = datiBaseProcedura;
  }

  public AppaltoP33Type datiBaseStrumentiProcedura(DatiBaseStrumentiProceduraSistemaDinamicoAstaType datiBaseStrumentiProcedura) {
    this.datiBaseStrumentiProcedura = datiBaseStrumentiProcedura;
    return this;
  }

   /**
   * Get datiBaseStrumentiProcedura
   * @return datiBaseStrumentiProcedura
  **/
  @Schema(description = "")
  public DatiBaseStrumentiProceduraSistemaDinamicoAstaType getDatiBaseStrumentiProcedura() {
    return datiBaseStrumentiProcedura;
  }

  public void setDatiBaseStrumentiProcedura(DatiBaseStrumentiProceduraSistemaDinamicoAstaType datiBaseStrumentiProcedura) {
    this.datiBaseStrumentiProcedura = datiBaseStrumentiProcedura;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppaltoP33Type appaltoP33Type = (AppaltoP33Type) o;
    return Objects.equals(this.cigAccordoQuadroConvenzione, appaltoP33Type.cigAccordoQuadroConvenzione) &&
        Objects.equals(this.datiBase, appaltoP33Type.datiBase) &&
        Objects.equals(this.datiBaseProcedura, appaltoP33Type.datiBaseProcedura) &&
        Objects.equals(this.datiBaseStrumentiProcedura, appaltoP33Type.datiBaseStrumentiProcedura) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cigAccordoQuadroConvenzione, datiBase, datiBaseProcedura, datiBaseStrumentiProcedura, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppaltoP33Type {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    cigAccordoQuadroConvenzione: ").append(toIndentedString(cigAccordoQuadroConvenzione)).append("\n");
    sb.append("    datiBase: ").append(toIndentedString(datiBase)).append("\n");
    sb.append("    datiBaseProcedura: ").append(toIndentedString(datiBaseProcedura)).append("\n");
    sb.append("    datiBaseStrumentiProcedura: ").append(toIndentedString(datiBaseStrumentiProcedura)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
