/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.MultilinguaType;
/**
 * Dato in comune con il Business Group Purpose delle eforms
 */
@Schema(description = "Dato in comune con il Business Group Purpose delle eforms")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:13:15.678079400+02:00[Europe/Berlin]")

public class DatiBaseAppaltoADType {
  @JsonProperty("oggetto")
  private String oggetto = null;

  @JsonProperty("oggettoMl")
  private MultilinguaType oggettoMl = null;

  public DatiBaseAppaltoADType oggetto(String oggetto) {
    this.oggetto = oggetto;
    return this;
  }

   /**
   * Oggetto gara - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-24 - Description del TED
   * @return oggetto
  **/
  @Schema(required = true, description = "Oggetto gara - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-24 - Description del TED")
  public String getOggetto() {
    return oggetto;
  }

  public void setOggetto(String oggetto) {
    this.oggetto = oggetto;
  }

  public DatiBaseAppaltoADType oggettoMl(MultilinguaType oggettoMl) {
    this.oggettoMl = oggettoMl;
    return this;
  }

   /**
   * Get oggettoMl
   * @return oggettoMl
  **/
  @Schema(description = "")
  public MultilinguaType getOggettoMl() {
    return oggettoMl;
  }

  public void setOggettoMl(MultilinguaType oggettoMl) {
    this.oggettoMl = oggettoMl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatiBaseAppaltoADType datiBaseAppaltoADType = (DatiBaseAppaltoADType) o;
    return Objects.equals(this.oggetto, datiBaseAppaltoADType.oggetto) &&
        Objects.equals(this.oggettoMl, datiBaseAppaltoADType.oggettoMl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oggetto, oggettoMl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatiBaseAppaltoADType {\n");
    
    sb.append("    oggetto: ").append(toIndentedString(oggetto)).append("\n");
    sb.append("    oggettoMl: ").append(toIndentedString(oggettoMl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
