/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * Dato in comune con il Business Group Submission Terms delle eforms
 */
@Schema(description = "Dato in comune con il Business Group Submission Terms delle eforms")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:13:15.678079400+02:00[Europe/Berlin]")

public class DatiBaseTerminiInvioSoloOraType {
  @JsonProperty("oraScadenzaPresentazioneOfferte")
  private java.time.OffsetDateTime oraScadenzaPresentazioneOfferte = null;

  public DatiBaseTerminiInvioSoloOraType oraScadenzaPresentazioneOfferte(java.time.OffsetDateTime oraScadenzaPresentazioneOfferte) {
    this.oraScadenzaPresentazioneOfferte = oraScadenzaPresentazioneOfferte;
    return this;
  }

   /**
   * Date e ora di scadenza per la presentazione delle offerte (hh:mm) - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-131 - Deadline Receipt Tenders del TED
   * @return oraScadenzaPresentazioneOfferte
  **/
  @Schema(required = true, description = "Date e ora di scadenza per la presentazione delle offerte (hh:mm) - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-131 - Deadline Receipt Tenders del TED")
  public java.time.OffsetDateTime getOraScadenzaPresentazioneOfferte() {
    return oraScadenzaPresentazioneOfferte;
  }

  public void setOraScadenzaPresentazioneOfferte(java.time.OffsetDateTime oraScadenzaPresentazioneOfferte) {
    this.oraScadenzaPresentazioneOfferte = oraScadenzaPresentazioneOfferte;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatiBaseTerminiInvioSoloOraType datiBaseTerminiInvioSoloOraType = (DatiBaseTerminiInvioSoloOraType) o;
    return Objects.equals(this.oraScadenzaPresentazioneOfferte, datiBaseTerminiInvioSoloOraType.oraScadenzaPresentazioneOfferte);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oraScadenzaPresentazioneOfferte);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatiBaseTerminiInvioSoloOraType {\n");
    
    sb.append("    oraScadenzaPresentazioneOfferte: ").append(toIndentedString(oraScadenzaPresentazioneOfferte)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
