/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.CodIstatEnum;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.DatiBaseAccessibilitaType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.DatiBaseAggiudicazioneOptionalType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.DatiBaseCPVType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.DatiBaseContrattoType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.DatiBaseImportoType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.DatiTerminiInvioType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.FinanziamentoType;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.LottoP23Type;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.MotivoEsclusioneOrdinarioSpecialeEnum;
import it.appaltiecontratti.pcp.v102.comunicaAppalto.QuadroEconomicoConcorsiProgettazioneType;
import java.util.List;
/**
 * LottoP223Type
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:13:15.678079400+02:00[Europe/Berlin]")

public class LottoP223Type extends LottoP23Type {
  @JsonProperty("datiBase")
  private AllOfLottoP223TypeDatiBase datiBase = null;

  @JsonProperty("datiBaseContratto")
  private DatiBaseContrattoType datiBaseContratto = null;

  @JsonProperty("datiBaseAggiudicazione")
  private DatiBaseAggiudicazioneOptionalType datiBaseAggiudicazione = null;

  @JsonProperty("datiBaseTerminiInvio")
  private DatiTerminiInvioType datiBaseTerminiInvio = null;

  @JsonProperty("datiBaseImporto")
  private DatiBaseImportoType datiBaseImporto = null;

  @JsonProperty("datiBaseCPV")
  private DatiBaseCPVType datiBaseCPV = null;

  @JsonProperty("datiBaseAccessibilita")
  private DatiBaseAccessibilitaType datiBaseAccessibilita = null;

  @JsonProperty("datiBaseDocumenti")
  private AllOfLottoP223TypeDatiBaseDocumenti datiBaseDocumenti = null;

  public LottoP223Type datiBase(AllOfLottoP223TypeDatiBase datiBase) {
    this.datiBase = datiBase;
    return this;
  }

   /**
   * Get datiBase
   * @return datiBase
  **/
  @Schema(required = true, description = "")
  public AllOfLottoP223TypeDatiBase getDatiBase() {
    return datiBase;
  }

  public void setDatiBase(AllOfLottoP223TypeDatiBase datiBase) {
    this.datiBase = datiBase;
  }

  public LottoP223Type datiBaseContratto(DatiBaseContrattoType datiBaseContratto) {
    this.datiBaseContratto = datiBaseContratto;
    return this;
  }

   /**
   * Get datiBaseContratto
   * @return datiBaseContratto
  **/
  @Schema(description = "")
  public DatiBaseContrattoType getDatiBaseContratto() {
    return datiBaseContratto;
  }

  public void setDatiBaseContratto(DatiBaseContrattoType datiBaseContratto) {
    this.datiBaseContratto = datiBaseContratto;
  }

  public LottoP223Type datiBaseAggiudicazione(DatiBaseAggiudicazioneOptionalType datiBaseAggiudicazione) {
    this.datiBaseAggiudicazione = datiBaseAggiudicazione;
    return this;
  }

   /**
   * Get datiBaseAggiudicazione
   * @return datiBaseAggiudicazione
  **/
  @Schema(description = "")
  public DatiBaseAggiudicazioneOptionalType getDatiBaseAggiudicazione() {
    return datiBaseAggiudicazione;
  }

  public void setDatiBaseAggiudicazione(DatiBaseAggiudicazioneOptionalType datiBaseAggiudicazione) {
    this.datiBaseAggiudicazione = datiBaseAggiudicazione;
  }

  public LottoP223Type datiBaseTerminiInvio(DatiTerminiInvioType datiBaseTerminiInvio) {
    this.datiBaseTerminiInvio = datiBaseTerminiInvio;
    return this;
  }

   /**
   * Get datiBaseTerminiInvio
   * @return datiBaseTerminiInvio
  **/
  @Schema(required = true, description = "")
  public DatiTerminiInvioType getDatiBaseTerminiInvio() {
    return datiBaseTerminiInvio;
  }

  public void setDatiBaseTerminiInvio(DatiTerminiInvioType datiBaseTerminiInvio) {
    this.datiBaseTerminiInvio = datiBaseTerminiInvio;
  }

  public LottoP223Type datiBaseImporto(DatiBaseImportoType datiBaseImporto) {
    this.datiBaseImporto = datiBaseImporto;
    return this;
  }

   /**
   * Get datiBaseImporto
   * @return datiBaseImporto
  **/
  @Schema(description = "")
  public DatiBaseImportoType getDatiBaseImporto() {
    return datiBaseImporto;
  }

  public void setDatiBaseImporto(DatiBaseImportoType datiBaseImporto) {
    this.datiBaseImporto = datiBaseImporto;
  }

  public LottoP223Type datiBaseCPV(DatiBaseCPVType datiBaseCPV) {
    this.datiBaseCPV = datiBaseCPV;
    return this;
  }

   /**
   * Get datiBaseCPV
   * @return datiBaseCPV
  **/
  @Schema(required = true, description = "")
  public DatiBaseCPVType getDatiBaseCPV() {
    return datiBaseCPV;
  }

  public void setDatiBaseCPV(DatiBaseCPVType datiBaseCPV) {
    this.datiBaseCPV = datiBaseCPV;
  }

  public LottoP223Type datiBaseAccessibilita(DatiBaseAccessibilitaType datiBaseAccessibilita) {
    this.datiBaseAccessibilita = datiBaseAccessibilita;
    return this;
  }

   /**
   * Get datiBaseAccessibilita
   * @return datiBaseAccessibilita
  **/
  @Schema(description = "")
  public DatiBaseAccessibilitaType getDatiBaseAccessibilita() {
    return datiBaseAccessibilita;
  }

  public void setDatiBaseAccessibilita(DatiBaseAccessibilitaType datiBaseAccessibilita) {
    this.datiBaseAccessibilita = datiBaseAccessibilita;
  }

  public LottoP223Type datiBaseDocumenti(AllOfLottoP223TypeDatiBaseDocumenti datiBaseDocumenti) {
    this.datiBaseDocumenti = datiBaseDocumenti;
    return this;
  }

   /**
   * Get datiBaseDocumenti
   * @return datiBaseDocumenti
  **/
  @Schema(required = true, description = "")
  public AllOfLottoP223TypeDatiBaseDocumenti getDatiBaseDocumenti() {
    return datiBaseDocumenti;
  }

  public void setDatiBaseDocumenti(AllOfLottoP223TypeDatiBaseDocumenti datiBaseDocumenti) {
    this.datiBaseDocumenti = datiBaseDocumenti;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LottoP223Type lottoP223Type = (LottoP223Type) o;
    return Objects.equals(this.datiBase, lottoP223Type.datiBase) &&
        Objects.equals(this.datiBaseContratto, lottoP223Type.datiBaseContratto) &&
        Objects.equals(this.datiBaseAggiudicazione, lottoP223Type.datiBaseAggiudicazione) &&
        Objects.equals(this.datiBaseTerminiInvio, lottoP223Type.datiBaseTerminiInvio) &&
        Objects.equals(this.datiBaseImporto, lottoP223Type.datiBaseImporto) &&
        Objects.equals(this.datiBaseCPV, lottoP223Type.datiBaseCPV) &&
        Objects.equals(this.datiBaseAccessibilita, lottoP223Type.datiBaseAccessibilita) &&
        Objects.equals(this.datiBaseDocumenti, lottoP223Type.datiBaseDocumenti) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datiBase, datiBaseContratto, datiBaseAggiudicazione, datiBaseTerminiInvio, datiBaseImporto, datiBaseCPV, datiBaseAccessibilita, datiBaseDocumenti, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LottoP223Type {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    datiBase: ").append(toIndentedString(datiBase)).append("\n");
    sb.append("    datiBaseContratto: ").append(toIndentedString(datiBaseContratto)).append("\n");
    sb.append("    datiBaseAggiudicazione: ").append(toIndentedString(datiBaseAggiudicazione)).append("\n");
    sb.append("    datiBaseTerminiInvio: ").append(toIndentedString(datiBaseTerminiInvio)).append("\n");
    sb.append("    datiBaseImporto: ").append(toIndentedString(datiBaseImporto)).append("\n");
    sb.append("    datiBaseCPV: ").append(toIndentedString(datiBaseCPV)).append("\n");
    sb.append("    datiBaseAccessibilita: ").append(toIndentedString(datiBaseAccessibilita)).append("\n");
    sb.append("    datiBaseDocumenti: ").append(toIndentedString(datiBaseDocumenti)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
