openapi: 3.0.3
info:
  title: Specifiche Servizi Appalto - OpenAPI 3.0
  x-summary: >-
    Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti
  description: |-
    Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.

      #### Documentazione
      La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:
        [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md)
    ```
  # I termini del servizio.
  termsOfService: 'https://github.com/anticorruzione/npa/blob/main/README.md#termini-del-servizio'
  # Chi posso contattare per informazioni sul servizio e sul suo stato?
  contact:
    email: ufficio.uscp@anticorruzione.it
    name: ANAC - Ufficio Servizi IT Contratti Pubblici
    url: https://www.anticorruzione.it
  # L'audience delle API. Attualmente e' definito solamente
  #   la tipologia `public`.
  x-audience:
    - public
  # Ogni API deve avere un UUID, invariante nel tempo e
  #   rispetto al `title`.
  x-api-id: 9deffff0-2486-11ee-be56-0242ac120002
  license:
    name: Licenza Pubblica dell'Unione Europea v. 1.2
    url: 'https://eupl.eu/1.2/it/'
  # Per dare indicazioni sul ciclo di vita dell'API
  # si puo' usare un parametro come:
  x-lifecycle:
    published: 2023-03-31
    maturity: published  
  version: 1.0.4
servers:
  - url: https://apigw-test.anticorruzione.it/modi/rest/ServiziComuni/v2
    description: Ambiente di Qualificazione
tags:
  - name: serviziComuni
    description: In questo contesto si riportano i servizi comuni, ossia quelli che possono essere richiamati dalle Stazioni appaltanti in più contesti della PCP.
  - name: serviziTecnici 
    description: Operazioni richiesti dalle linee guida sull'interoperabilità
paths:
  /status:
    get:
      summary: Ritorna lo stato dell'applicazione. SINCRONO
      description: |
        Ritorna lo stato dell'applicazione. A scopo
        di test, su base randomica puo' ritornare
        un errore.
      operationId: idStatusShow
      tags:
        - serviziTecnici
      responses:
        '200':
            description: |
              Il server ha ritornato lo status. In caso di problemi
              ritorna sempre un problem+json.
            headers: &ratelimit_headers 
              X-RateLimit-Limit:
                 $ref: '#/components/headers/X-RateLimit-Limit'
              X-RateLimit-Remaining:
                 $ref: '#/components/headers/X-RateLimit-Remaining'
              X-RateLimit-Reset:
                 $ref: '#/components/headers/X-RateLimit-Reset'
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/BaseResponse'
        '429':
            description: Limite di richieste raggiunto
            headers:
              Retry-After:
                $ref: '#/components/headers/Retry-After'
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/BaseResponse'        
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BaseResponse'         
  /stato-appalto:
    get:
      tags:
         - serviziComuni
      summary: API Rest per il recupero dello stato dell'Appalto, del Lotto o del Contratto. SINCRONO
      description: Servizio per il recupero dello stato in cui si trova l’Appalto, il Lotto o il Contratto. Il compito dispositivo di aggiornare lo stato proveniente dai sistemi esterni, TED e/o PPL-ANAC, sarà in carico ad un task schedulato PCP. Pertanto il recupero dello stato da parte del servizio insiste su uno stato PCP che restituisce anche la data in cui il task schedulato ha effettuato il controllo sui sistemi esterni. SINCRONO
      operationId: idAppaltoStato
      parameters:
        - in: query
          name: idAppalto
          description: Identificativo univoco dell'Appalto definito da ANAC. Alternativo agli altri parametri di input.
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        - in: query
          name: cig
          description: Identificativo univoco Gara-Lotto rilasciato da ANAC. Alternativo agli altri parametri di input.
          schema:
            type: string
            example: 9050626CD6
        - in: query
          name: idContratto
          description: Identificativo univoco del Contratto definito da ANAC. Alternativo agli altri parametri di input.
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"   
      responses:
        '200':
          description: Operazione terminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatoResponse'  
        '400':
            $ref: '#/components/responses/400BadRequest'
        '404':
            $ref: '#/components/responses/404NotFound'
        '429':
            $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
      security:
        - apiKeyAuth: []
  /esito-operazione:
    get:
      tags:
        - serviziComuni
      summary: API Rest per il recupero dell'esito dell'operazione. SINCRONO
      description: Il compito dispositivo di aggiornare l'esito delle operazioni provenienti dai sistemi esterni, TED e/o PPL-ANAC, sarà in carico ad un task schedulato PCP. Pertanto il recupero dell'esito operazione da parte del servizio insiste su uno stato dell'esito PCP che restituisce anche la data in cui il task schedulato ha effettuato il controllo sui sistemi esterni. SINCRONO
      operationId: idOperazioneEsito
      parameters:
        - in: query
          name: idAppalto
          description: identificativo univoco dell'Appalto definito da ANAC. Obbligatorio se idPianificazione non è stato valorizzato (A UUID specified by RFC4122)
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"
        - in: query
          name: idPianificazione
          description: identificativo univoco della Pianificazione definito da ANAC. Obbligatorio se idAppalto non è stato valorizzato (A UUID specified by RFC4122)
          schema:
            type: string
            format: uuid
            example: "f81d4fae-7dec-11d0-a765-00a0c91e6bf6"            
        - in: query
          name: tipoOperazione
          description: Tipo operazione di cui si vuole conoscere l'esito - fare riferimento ai valori contenuti nel file [tipoOperazione.json](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/tipoOperazione.json)
          required: true
          schema:
            type: string
            example: "SC_VERIF"
        - in: query
          name: tipoRicerca
          description: Codice Tipo di ricerca da eseguire - fare riferimento ai valori contenuti nel file [tipoRicercaOperazione.json](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/tipoRicercaOperazione.json)
          required: true
          schema:
            type: string
            example: "ULTIMO_ESITO"
        - in: query
          name: esito
          description: Codice sintetico esito operazione - fare riferimento ai valori contenuti nel file [esito.json](https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/tipologiche/esito.json)
          schema:
            type: string
            example: "OK"
      responses:
        '200':
          description: Esecuzione avvenuta con successo
          headers: *ratelimit_headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EsitoOperazioneListaResponse'
        '404':
            description: Identificativo non trovato
            headers: *ratelimit_headers
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
        '400':
            description: Richiesta malformata
            headers: *ratelimit_headers
            content:
             application/problem+json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
        '429':
            description: Limite di richieste raggiunto
            headers:
              Retry-After:
                $ref: '#/components/headers/Retry-After'
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
        '500':
            description: Errore interno avvenuto
            content:
              application/problem+json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
      security:
        - apiKeyAuth: []
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    Sunset:
      description: The Sunset HTTP response header field, indicates that a URI is likely
        to become unresponsive at a specified point in the future.  It also defines
        a sunset link relation type that allows linking to resources providing information
        about an upcoming resource or service sunset.
      schema:
        example: Sun, 06 Nov 1994 08:49:37 GMT
        externalDocs:
          url: https://tools.ietf.org/html/rfc7231#appendix-D
        format: HTTP-date
        maxLength: 30
        type: string
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer  
    X-Ratelimit-Used: 
      description: The number of requests used in the current period
      schema:
        type: integer
        format: int32      
  responses:
    200AckResponse:
      description: Richiesta accettata
      headers: *ratelimit_headers
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AckResponse'
    400BadRequest:
      description: Richiesta malformattata
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    404NotFound:
      description: Dato non trovato
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    429TooManyRequests:
      description: Limite di richieste raggiunto
      headers:
        Retry-After:
            $ref: '#/components/headers/Retry-After'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    500InternalServerError:
      description: Errore generico. Operazione terminato con errore. Viene restitutito il dettaglio dell'errore
      headers: *ratelimit_headers
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    503ServiceUnavailable:
      description: Service Unavailable
      headers:
        Retry-After:
            $ref: '#/components/headers/Retry-After'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    default:
      description: |-
       Errore inatteso. Non ritornare informazioni
       sulla logica interna e/o non pertinenti all'interfaccia.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErroriEnum:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-tipologiche.yaml#/components/schemas/ErroriEnum'
    StatoType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/StatoType'      
    EsitoOperazioneType:
      $ref: 'https://raw.githubusercontent.com/anticorruzione/npa/main/docs/modello-dati/modello-dati-npa.yaml#/components/schemas/EsitoOperazioneType'
    StatoResponse: 
      allOf: # estende lo schema dati di BaseResponse e StatoType
        - $ref: '#/components/schemas/BaseResponse'
        - $ref: '#/components/schemas/StatoType'
      type: object
      additionalProperties: false      
    EsitoOperazioneListaResponse:
      allOf: # estende lo schema dati di BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        listaEsiti:
          description: Lista di ritorno esiti operazione
          type: array
          items:
            $ref: '#/components/schemas/EsitoOperazioneType'
    BaseResponse:
      type: object
      additionalProperties: false
      properties:
          instance:
              description: |
                An absolute URI that identifies the specific occurrence of the
                problem.
                It may or may not yield further information if dereferenced.
              format: uri
              maxLength: 2048
              type: string
          status:
              description: |
                The HTTP status code generated by the origin server for this
                occurrence
                of the problem.
              exclusiveMaximum: true
              format: int32
              maximum: 600
              minimum: 100
              type: integer
              example: 400
          title:
              description: |
                A short, summary of the problem type. Written in english and
                readable
                for engineers (usually not suited for non technical stakeholders
                and not localized);
              maxLength: 64
              pattern: ^[ -~]{0,64}$
              type: string
              example: 'There was a validation error'
          detail:
              description: |
                A human readable explanation specific to this occurrence of the
                problem.
              maxLength: 4096
              pattern: ^.{0,1024}$
              type: string
              example: 'Object Validation Error'
          type:
              description: |
                An absolute URI that identifies the problem type. When
                dereferenced,
                it SHOULD provide human-readable documentation for the problem
                type
                (e.g., using HTML).
              default: about:blank
              format: uri
              maxLength: 2048
              type: string
              example: 'https://tools.ietf.org/html/rfc7231#section-6.6.4'
    ErrorResponse:
      allOf: # estende la classe BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      properties:
        errori: 
          description: elenco degli errori
          type: array
          items:
            $ref: '#/components/schemas/ErroriEnum'
    AckResponse:
      allOf: # estende la classe BaseResponse
        - $ref: '#/components/schemas/BaseResponse'
      example:
        status: 200
        title: "Richiesta acquisita"
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: apiKeyAuth # name of the header, query parameter or cookie
      in: header  # can be "header", "query" or "cookie"