/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.MotiviVariazioneAnagraficaEnum;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.PartecipanteType;
/**
 * Dati relativi alla Variazione Aggiudicatari/Costituzione della società di scopo.
 */
@Schema(description = "Dati relativi alla Variazione Aggiudicatari/Costituzione della società di scopo.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:29.128631100+02:00[Europe/Rome]")

public class AnacFormS4Type {
  @JsonProperty("cig")
  private String cig = null;

  @JsonProperty("partecipante")
  private PartecipanteType partecipante = null;

  @JsonProperty("motivoVariazione")
  private MotiviVariazioneAnagraficaEnum motivoVariazione = null;

  public AnacFormS4Type cig(String cig) {
    this.cig = cig;
    return this;
  }

   /**
   * codice identificativo lotto
   * @return cig
  **/
  @Schema(required = true, description = "codice identificativo lotto")
  public String getCig() {
    return cig;
  }

  public void setCig(String cig) {
    this.cig = cig;
  }

  public AnacFormS4Type partecipante(PartecipanteType partecipante) {
    this.partecipante = partecipante;
    return this;
  }

   /**
   * Get partecipante
   * @return partecipante
  **/
  @Schema(description = "")
  public PartecipanteType getPartecipante() {
    return partecipante;
  }

  public void setPartecipante(PartecipanteType partecipante) {
    this.partecipante = partecipante;
  }

  public AnacFormS4Type motivoVariazione(MotiviVariazioneAnagraficaEnum motivoVariazione) {
    this.motivoVariazione = motivoVariazione;
    return this;
  }

   /**
   * Get motivoVariazione
   * @return motivoVariazione
  **/
  @Schema(description = "")
  public MotiviVariazioneAnagraficaEnum getMotivoVariazione() {
    return motivoVariazione;
  }

  public void setMotivoVariazione(MotiviVariazioneAnagraficaEnum motivoVariazione) {
    this.motivoVariazione = motivoVariazione;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnacFormS4Type anacFormS4Type = (AnacFormS4Type) o;
    return Objects.equals(this.cig, anacFormS4Type.cig) &&
        Objects.equals(this.partecipante, anacFormS4Type.partecipante) &&
        Objects.equals(this.motivoVariazione, anacFormS4Type.motivoVariazione);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cig, partecipante, motivoVariazione);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnacFormS4Type {\n");
    
    sb.append("    cig: ").append(toIndentedString(cig)).append("\n");
    sb.append("    partecipante: ").append(toIndentedString(partecipante)).append("\n");
    sb.append("    motivoVariazione: ").append(toIndentedString(motivoVariazione)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
