/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.ModificaContrattuale40Type;
import java.util.UUID;
/**
 * Contiene tutti i dati relativi alle modifiche contrattuali
 */
@Schema(description = "Contiene tutti i dati relativi alle modifiche contrattuali")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:29.128631100+02:00[Europe/Rome]")

public class AnacFormM140Type {
  @JsonProperty("idContratto")
  private UUID idContratto = null;

  @JsonProperty("modificaContrattuale")
  private ModificaContrattuale40Type modificaContrattuale = null;

  public AnacFormM140Type idContratto(UUID idContratto) {
    this.idContratto = idContratto;
    return this;
  }

   /**
   * identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.
   * @return idContratto
  **/
  @Schema(example = "f81d4fae-7dec-11d0-a765-00a0c91e6bf6", required = true, description = "identificativo del contratto restituito in response alla scheda di Sottoscrizione del contratto.")
  public UUID getIdContratto() {
    return idContratto;
  }

  public void setIdContratto(UUID idContratto) {
    this.idContratto = idContratto;
  }

  public AnacFormM140Type modificaContrattuale(ModificaContrattuale40Type modificaContrattuale) {
    this.modificaContrattuale = modificaContrattuale;
    return this;
  }

   /**
   * Get modificaContrattuale
   * @return modificaContrattuale
  **/
  @Schema(required = true, description = "")
  public ModificaContrattuale40Type getModificaContrattuale() {
    return modificaContrattuale;
  }

  public void setModificaContrattuale(ModificaContrattuale40Type modificaContrattuale) {
    this.modificaContrattuale = modificaContrattuale;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnacFormM140Type anacFormM140Type = (AnacFormM140Type) o;
    return Objects.equals(this.idContratto, anacFormM140Type.idContratto) &&
        Objects.equals(this.modificaContrattuale, anacFormM140Type.modificaContrattuale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idContratto, modificaContrattuale);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnacFormM140Type {\n");
    
    sb.append("    idContratto: ").append(toIndentedString(idContratto)).append("\n");
    sb.append("    modificaContrattuale: ").append(toIndentedString(modificaContrattuale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
