/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.SubappaltoType1;
import java.util.UUID;
/**
 * Contiene tutti i dati relativi alla scheda di Richiesta di Subappalto
 */
@Schema(description = "Contiene tutti i dati relativi alla scheda di Richiesta di Subappalto")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:29.128631100+02:00[Europe/Rome]")

public class AnacFormES1Type {
  @JsonProperty("idScheda")
  private UUID idScheda = null;

  @JsonProperty("subappalto")
  private SubappaltoType1 subappalto = null;

  public AnacFormES1Type idScheda(UUID idScheda) {
    this.idScheda = idScheda;
    return this;
  }

   /**
   * identificativo restituito dal servizio all’invio della scheda di richiesta di subappalto.
   * @return idScheda
  **/
  @Schema(example = "f81d4fae-7dec-11d0-a765-00a0c91e6bf6", required = true, description = "identificativo restituito dal servizio all’invio della scheda di richiesta di subappalto.")
  public UUID getIdScheda() {
    return idScheda;
  }

  public void setIdScheda(UUID idScheda) {
    this.idScheda = idScheda;
  }

  public AnacFormES1Type subappalto(SubappaltoType1 subappalto) {
    this.subappalto = subappalto;
    return this;
  }

   /**
   * Get subappalto
   * @return subappalto
  **/
  @Schema(required = true, description = "")
  public SubappaltoType1 getSubappalto() {
    return subappalto;
  }

  public void setSubappalto(SubappaltoType1 subappalto) {
    this.subappalto = subappalto;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnacFormES1Type anacFormES1Type = (AnacFormES1Type) o;
    return Objects.equals(this.idScheda, anacFormES1Type.idScheda) &&
        Objects.equals(this.subappalto, anacFormES1Type.subappalto);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idScheda, subappalto);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnacFormES1Type {\n");
    
    sb.append("    idScheda: ").append(toIndentedString(idScheda)).append("\n");
    sb.append("    subappalto: ").append(toIndentedString(subappalto)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
