/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.AppaltoA130Type;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.DatiBaseProceduraACompletoType;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.DatiBaseStrumentiProceduraAType;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.DatiBaseSubappaltiRequiredType;
/**
 * AppaltoA230Type
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:29.128631100+02:00[Europe/Rome]")

public class AppaltoA230Type extends AppaltoA130Type {
  @JsonProperty("datiBaseSubappalti")
  private DatiBaseSubappaltiRequiredType datiBaseSubappalti = null;

  @JsonProperty("datiBaseProcedura")
  private DatiBaseProceduraACompletoType datiBaseProcedura = null;

  @JsonProperty("datiBaseStrumentiProcedura")
  private DatiBaseStrumentiProceduraAType datiBaseStrumentiProcedura = null;

  public AppaltoA230Type datiBaseSubappalti(DatiBaseSubappaltiRequiredType datiBaseSubappalti) {
    this.datiBaseSubappalti = datiBaseSubappalti;
    return this;
  }

   /**
   * Get datiBaseSubappalti
   * @return datiBaseSubappalti
  **/
  @Schema(required = true, description = "")
  public DatiBaseSubappaltiRequiredType getDatiBaseSubappalti() {
    return datiBaseSubappalti;
  }

  public void setDatiBaseSubappalti(DatiBaseSubappaltiRequiredType datiBaseSubappalti) {
    this.datiBaseSubappalti = datiBaseSubappalti;
  }

  public AppaltoA230Type datiBaseProcedura(DatiBaseProceduraACompletoType datiBaseProcedura) {
    this.datiBaseProcedura = datiBaseProcedura;
    return this;
  }

   /**
   * Get datiBaseProcedura
   * @return datiBaseProcedura
  **/
  @Schema(required = true, description = "")
  public DatiBaseProceduraACompletoType getDatiBaseProcedura() {
    return datiBaseProcedura;
  }

  public void setDatiBaseProcedura(DatiBaseProceduraACompletoType datiBaseProcedura) {
    this.datiBaseProcedura = datiBaseProcedura;
  }

  public AppaltoA230Type datiBaseStrumentiProcedura(DatiBaseStrumentiProceduraAType datiBaseStrumentiProcedura) {
    this.datiBaseStrumentiProcedura = datiBaseStrumentiProcedura;
    return this;
  }

   /**
   * Get datiBaseStrumentiProcedura
   * @return datiBaseStrumentiProcedura
  **/
  @Schema(required = true, description = "")
  public DatiBaseStrumentiProceduraAType getDatiBaseStrumentiProcedura() {
    return datiBaseStrumentiProcedura;
  }

  public void setDatiBaseStrumentiProcedura(DatiBaseStrumentiProceduraAType datiBaseStrumentiProcedura) {
    this.datiBaseStrumentiProcedura = datiBaseStrumentiProcedura;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppaltoA230Type appaltoA230Type = (AppaltoA230Type) o;
    return Objects.equals(this.datiBaseSubappalti, appaltoA230Type.datiBaseSubappalti) &&
        Objects.equals(this.datiBaseProcedura, appaltoA230Type.datiBaseProcedura) &&
        Objects.equals(this.datiBaseStrumentiProcedura, appaltoA230Type.datiBaseStrumentiProcedura) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datiBaseSubappalti, datiBaseProcedura, datiBaseStrumentiProcedura, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppaltoA230Type {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    datiBaseSubappalti: ").append(toIndentedString(datiBaseSubappalti)).append("\n");
    sb.append("    datiBaseProcedura: ").append(toIndentedString(datiBaseProcedura)).append("\n");
    sb.append("    datiBaseStrumentiProcedura: ").append(toIndentedString(datiBaseStrumentiProcedura)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
