/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.CPVEnum;
/**
 * cpv prevalente o secondaria
 */
@Schema(description = "cpv prevalente o secondaria")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-25T11:43:52.162087800+01:00[Europe/Rome]")

public class CpvType {
  @JsonProperty("cpv")
  private CPVEnum cpv = null;

  /**
   * tipo di categoria
   */
  public enum TipoEnum {
    PREVALENTE("PREVALENTE"),
    SECONDARIA("SECONDARIA");

    private String value;

    TipoEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TipoEnum fromValue(String input) {
      for (TipoEnum b : TipoEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("tipo")
  private TipoEnum tipo = null;

  public CpvType cpv(CPVEnum cpv) {
    this.cpv = cpv;
    return this;
  }

   /**
   * Get cpv
   * @return cpv
  **/
  @Schema(required = true, description = "")
  public CPVEnum getCpv() {
    return cpv;
  }

  public void setCpv(CPVEnum cpv) {
    this.cpv = cpv;
  }

  public CpvType tipo(TipoEnum tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * tipo di categoria
   * @return tipo
  **/
  @Schema(required = true, description = "tipo di categoria")
  public TipoEnum getTipo() {
    return tipo;
  }

  public void setTipo(TipoEnum tipo) {
    this.tipo = tipo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CpvType cpvType = (CpvType) o;
    return Objects.equals(this.cpv, cpvType.cpv) &&
        Objects.equals(this.tipo, cpvType.tipo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpv, tipo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CpvType {\n");
    
    sb.append("    cpv: ").append(toIndentedString(cpv)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
