/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.EsitoProceduraAnnullataEnum;
/**
 * dati relativi ai lotti
 */
@Schema(description = "dati relativi ai lotti")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:29.128631100+02:00[Europe/Rome]")

public class LottoNAGType {
  @JsonProperty("cig")
  private String cig = null;

  @JsonProperty("datiBaseRisultatoProcedura")
  private AllOfLottoNAGTypeDatiBaseRisultatoProcedura datiBaseRisultatoProcedura = null;

  @JsonProperty("esitoProceduraAnnullata")
  private EsitoProceduraAnnullataEnum esitoProceduraAnnullata = null;

  public LottoNAGType cig(String cig) {
    this.cig = cig;
    return this;
  }

   /**
   * codice identificativo lotto
   * @return cig
  **/
  @Schema(required = true, description = "codice identificativo lotto")
  public String getCig() {
    return cig;
  }

  public void setCig(String cig) {
    this.cig = cig;
  }

  public LottoNAGType datiBaseRisultatoProcedura(AllOfLottoNAGTypeDatiBaseRisultatoProcedura datiBaseRisultatoProcedura) {
    this.datiBaseRisultatoProcedura = datiBaseRisultatoProcedura;
    return this;
  }

   /**
   * Get datiBaseRisultatoProcedura
   * @return datiBaseRisultatoProcedura
  **/
  @Schema(required = true, description = "")
  public AllOfLottoNAGTypeDatiBaseRisultatoProcedura getDatiBaseRisultatoProcedura() {
    return datiBaseRisultatoProcedura;
  }

  public void setDatiBaseRisultatoProcedura(AllOfLottoNAGTypeDatiBaseRisultatoProcedura datiBaseRisultatoProcedura) {
    this.datiBaseRisultatoProcedura = datiBaseRisultatoProcedura;
  }

  public LottoNAGType esitoProceduraAnnullata(EsitoProceduraAnnullataEnum esitoProceduraAnnullata) {
    this.esitoProceduraAnnullata = esitoProceduraAnnullata;
    return this;
  }

   /**
   * Get esitoProceduraAnnullata
   * @return esitoProceduraAnnullata
  **/
  @Schema(description = "")
  public EsitoProceduraAnnullataEnum getEsitoProceduraAnnullata() {
    return esitoProceduraAnnullata;
  }

  public void setEsitoProceduraAnnullata(EsitoProceduraAnnullataEnum esitoProceduraAnnullata) {
    this.esitoProceduraAnnullata = esitoProceduraAnnullata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LottoNAGType lottoNAGType = (LottoNAGType) o;
    return Objects.equals(this.cig, lottoNAGType.cig) &&
        Objects.equals(this.datiBaseRisultatoProcedura, lottoNAGType.datiBaseRisultatoProcedura) &&
        Objects.equals(this.esitoProceduraAnnullata, lottoNAGType.esitoProceduraAnnullata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cig, datiBaseRisultatoProcedura, esitoProceduraAnnullata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LottoNAGType {\n");
    
    sb.append("    cig: ").append(toIndentedString(cig)).append("\n");
    sb.append("    datiBaseRisultatoProcedura: ").append(toIndentedString(datiBaseRisultatoProcedura)).append("\n");
    sb.append("    esitoProceduraAnnullata: ").append(toIndentedString(esitoProceduraAnnullata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
