/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.BaseResponse;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.PaginazioneType;
import it.appaltiecontratti.pcp.v1021.comunicaPostPubblicazione.SchedaType;
import java.util.ArrayList;
import java.util.List;
/**
 * Oggetto generico di ritorno di una risposta con paginazione
 */
@Schema(description = "Oggetto generico di ritorno di una risposta con paginazione")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:29.128631100+02:00[Europe/Rome]")

public class SchedaListaResponse extends BaseResponse {
  @JsonProperty("totRows")
  private Integer totRows = null;

  @JsonProperty("totPages")
  private Integer totPages = null;

  @JsonProperty("currentPage")
  private Integer currentPage = null;

  @JsonProperty("elementPage")
  private Integer elementPage = null;

  @JsonProperty("result")
  private List<SchedaType> result = null;

  public SchedaListaResponse totRows(Integer totRows) {
    this.totRows = totRows;
    return this;
  }

   /**
   * Numero totale di record risultante dalla ricerca
   * @return totRows
  **/
  @Schema(description = "Numero totale di record risultante dalla ricerca")
  public Integer getTotRows() {
    return totRows;
  }

  public void setTotRows(Integer totRows) {
    this.totRows = totRows;
  }

  public SchedaListaResponse totPages(Integer totPages) {
    this.totPages = totPages;
    return this;
  }

   /**
   * Numero totale di pagine risultanti dalla ricerca
   * @return totPages
  **/
  @Schema(description = "Numero totale di pagine risultanti dalla ricerca")
  public Integer getTotPages() {
    return totPages;
  }

  public void setTotPages(Integer totPages) {
    this.totPages = totPages;
  }

  public SchedaListaResponse currentPage(Integer currentPage) {
    this.currentPage = currentPage;
    return this;
  }

   /**
   * Numero di pagina corrente
   * @return currentPage
  **/
  @Schema(description = "Numero di pagina corrente")
  public Integer getCurrentPage() {
    return currentPage;
  }

  public void setCurrentPage(Integer currentPage) {
    this.currentPage = currentPage;
  }

  public SchedaListaResponse elementPage(Integer elementPage) {
    this.elementPage = elementPage;
    return this;
  }

   /**
   * Numero di elementi per pagina
   * @return elementPage
  **/
  @Schema(description = "Numero di elementi per pagina")
  public Integer getElementPage() {
    return elementPage;
  }

  public void setElementPage(Integer elementPage) {
    this.elementPage = elementPage;
  }

  public SchedaListaResponse result(List<SchedaType> result) {
    this.result = result;
    return this;
  }

  public SchedaListaResponse addResultItem(SchedaType resultItem) {
    if (this.result == null) {
      this.result = new ArrayList<>();
    }
    this.result.add(resultItem);
    return this;
  }

   /**
   * Lista di ritorno con la sintesi dei dati delle schede
   * @return result
  **/
  @Schema(description = "Lista di ritorno con la sintesi dei dati delle schede")
  public List<SchedaType> getResult() {
    return result;
  }

  public void setResult(List<SchedaType> result) {
    this.result = result;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchedaListaResponse schedaListaResponse = (SchedaListaResponse) o;
    return Objects.equals(this.totRows, schedaListaResponse.totRows) &&
        Objects.equals(this.totPages, schedaListaResponse.totPages) &&
        Objects.equals(this.currentPage, schedaListaResponse.currentPage) &&
        Objects.equals(this.elementPage, schedaListaResponse.elementPage) &&
        Objects.equals(this.result, schedaListaResponse.result) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totRows, totPages, currentPage, elementPage, result, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchedaListaResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    totRows: ").append(toIndentedString(totRows)).append("\n");
    sb.append("    totPages: ").append(toIndentedString(totPages)).append("\n");
    sb.append("    currentPage: ").append(toIndentedString(currentPage)).append("\n");
    sb.append("    elementPage: ").append(toIndentedString(elementPage)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
