/*
 * npa-gateway-ms API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.npaGateway;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AnagraficaOEType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:57.938746400+02:00[Europe/Rome]")

public class AnagraficaOEType {
  @JsonProperty("codiceFiscale")
  private String codiceFiscale = null;

  @JsonProperty("personaGiuridica")
  private String personaGiuridica = null;

  public AnagraficaOEType codiceFiscale(String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
    return this;
  }

   /**
   * Get codiceFiscale
   * @return codiceFiscale
  **/
  @Schema(description = "")
  public String getCodiceFiscale() {
    return codiceFiscale;
  }

  public void setCodiceFiscale(String codiceFiscale) {
    this.codiceFiscale = codiceFiscale;
  }

  public AnagraficaOEType personaGiuridica(String personaGiuridica) {
    this.personaGiuridica = personaGiuridica;
    return this;
  }

   /**
   * Get personaGiuridica
   * @return personaGiuridica
  **/
  @Schema(description = "")
  public String getPersonaGiuridica() {
    return personaGiuridica;
  }

  public void setPersonaGiuridica(String personaGiuridica) {
    this.personaGiuridica = personaGiuridica;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnagraficaOEType anagraficaOEType = (AnagraficaOEType) o;
    return Objects.equals(this.codiceFiscale, anagraficaOEType.codiceFiscale) &&
        Objects.equals(this.personaGiuridica, anagraficaOEType.personaGiuridica);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codiceFiscale, personaGiuridica);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnagraficaOEType {\n");
    
    sb.append("    codiceFiscale: ").append(toIndentedString(codiceFiscale)).append("\n");
    sb.append("    personaGiuridica: ").append(toIndentedString(personaGiuridica)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
