/*
 * npa-gateway-ms API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.npaGateway;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.npaGateway.ErroriEnum;
import it.appaltiecontratti.pcp.v1021.npaGateway.TipologicaSchemaErroriType;
import java.util.ArrayList;
import java.util.List;
/**
 * Wrapper risposte
 */
@Schema(description = "Wrapper risposte")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:57.938746400+02:00[Europe/Rome]")

public class InlineResponse400 {
  @JsonProperty("done")
  private String done = null;

  @JsonProperty("validationErrors")
  private List<TipologicaSchemaErroriType> validationErrors = null;

  @JsonProperty("internalErrors")
  private List<String> internalErrors = null;

  @JsonProperty("anacErrors")
  private List<ErroriEnum> anacErrors = null;

  @JsonProperty("govwayMessageId")
  private String govwayMessageId = null;

  @JsonProperty("govwayTransactionId")
  private String govwayTransactionId = null;

  @JsonProperty("cartId")
  private String cartId = null;

  @JsonProperty("data")
  private Object data = null;

  public InlineResponse400 done(String done) {
    this.done = done;
    return this;
  }

   /**
   * Esito operazione (Y o N)
   * @return done
  **/
  @Schema(description = "Esito operazione (Y o N)")
  public String getDone() {
    return done;
  }

  public void setDone(String done) {
    this.done = done;
  }

  public InlineResponse400 validationErrors(List<TipologicaSchemaErroriType> validationErrors) {
    this.validationErrors = validationErrors;
    return this;
  }

  public InlineResponse400 addValidationErrorsItem(TipologicaSchemaErroriType validationErrorsItem) {
    if (this.validationErrors == null) {
      this.validationErrors = new ArrayList<>();
    }
    this.validationErrors.add(validationErrorsItem);
    return this;
  }

   /**
   * Lista errori di validazione schede
   * @return validationErrors
  **/
  @Schema(description = "Lista errori di validazione schede")
  public List<TipologicaSchemaErroriType> getValidationErrors() {
    return validationErrors;
  }

  public void setValidationErrors(List<TipologicaSchemaErroriType> validationErrors) {
    this.validationErrors = validationErrors;
  }

  public InlineResponse400 internalErrors(List<String> internalErrors) {
    this.internalErrors = internalErrors;
    return this;
  }

  public InlineResponse400 addInternalErrorsItem(String internalErrorsItem) {
    if (this.internalErrors == null) {
      this.internalErrors = new ArrayList<>();
    }
    this.internalErrors.add(internalErrorsItem);
    return this;
  }

   /**
   * Lista errori interni
   * @return internalErrors
  **/
  @Schema(description = "Lista errori interni")
  public List<String> getInternalErrors() {
    return internalErrors;
  }

  public void setInternalErrors(List<String> internalErrors) {
    this.internalErrors = internalErrors;
  }

  public InlineResponse400 anacErrors(List<ErroriEnum> anacErrors) {
    this.anacErrors = anacErrors;
    return this;
  }

  public InlineResponse400 addAnacErrorsItem(ErroriEnum anacErrorsItem) {
    if (this.anacErrors == null) {
      this.anacErrors = new ArrayList<>();
    }
    this.anacErrors.add(anacErrorsItem);
    return this;
  }

   /**
   * Lista errori anac
   * @return anacErrors
  **/
  @Schema(description = "Lista errori anac")
  public List<ErroriEnum> getAnacErrors() {
    return anacErrors;
  }

  public void setAnacErrors(List<ErroriEnum> anacErrors) {
    this.anacErrors = anacErrors;
  }

  public InlineResponse400 govwayMessageId(String govwayMessageId) {
    this.govwayMessageId = govwayMessageId;
    return this;
  }

   /**
   * Govway Message Id
   * @return govwayMessageId
  **/
  @Schema(description = "Govway Message Id")
  public String getGovwayMessageId() {
    return govwayMessageId;
  }

  public void setGovwayMessageId(String govwayMessageId) {
    this.govwayMessageId = govwayMessageId;
  }

  public InlineResponse400 govwayTransactionId(String govwayTransactionId) {
    this.govwayTransactionId = govwayTransactionId;
    return this;
  }

   /**
   * Govway Transaction Id
   * @return govwayTransactionId
  **/
  @Schema(description = "Govway Transaction Id")
  public String getGovwayTransactionId() {
    return govwayTransactionId;
  }

  public void setGovwayTransactionId(String govwayTransactionId) {
    this.govwayTransactionId = govwayTransactionId;
  }

  public InlineResponse400 cartId(String cartId) {
    this.cartId = cartId;
    return this;
  }

   /**
   * CART Id
   * @return cartId
  **/
  @Schema(description = "CART Id")
  public String getCartId() {
    return cartId;
  }

  public void setCartId(String cartId) {
    this.cartId = cartId;
  }

  public InlineResponse400 data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * Oggetto di risposta
   * @return data
  **/
  @Schema(description = "Oggetto di risposta")
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse400 inlineResponse400 = (InlineResponse400) o;
    return Objects.equals(this.done, inlineResponse400.done) &&
        Objects.equals(this.validationErrors, inlineResponse400.validationErrors) &&
        Objects.equals(this.internalErrors, inlineResponse400.internalErrors) &&
        Objects.equals(this.anacErrors, inlineResponse400.anacErrors) &&
        Objects.equals(this.govwayMessageId, inlineResponse400.govwayMessageId) &&
        Objects.equals(this.govwayTransactionId, inlineResponse400.govwayTransactionId) &&
        Objects.equals(this.cartId, inlineResponse400.cartId) &&
        Objects.equals(this.data, inlineResponse400.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(done, validationErrors, internalErrors, anacErrors, govwayMessageId, govwayTransactionId, cartId, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse400 {\n");
    
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("    validationErrors: ").append(toIndentedString(validationErrors)).append("\n");
    sb.append("    internalErrors: ").append(toIndentedString(internalErrors)).append("\n");
    sb.append("    anacErrors: ").append(toIndentedString(anacErrors)).append("\n");
    sb.append("    govwayMessageId: ").append(toIndentedString(govwayMessageId)).append("\n");
    sb.append("    govwayTransactionId: ").append(toIndentedString(govwayTransactionId)).append("\n");
    sb.append("    cartId: ").append(toIndentedString(cartId)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
