/*
 * npa-gateway-ms API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.npaGateway;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PresaCaricoRequestDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:57.938746400+02:00[Europe/Rome]")

public class PresaCaricoRequestDTO {
  @JsonProperty("idAppalto")
  private String idAppalto = null;

  @JsonProperty("cig")
  private String cig = null;

  public PresaCaricoRequestDTO idAppalto(String idAppalto) {
    this.idAppalto = idAppalto;
    return this;
  }

   /**
   * Identificativo univoco dell&#x27;Appalto definito da ANAC. Alternativo al CIG
   * @return idAppalto
  **/
  @Schema(required = true, description = "Identificativo univoco dell'Appalto definito da ANAC. Alternativo al CIG")
  public String getIdAppalto() {
    return idAppalto;
  }

  public void setIdAppalto(String idAppalto) {
    this.idAppalto = idAppalto;
  }

  public PresaCaricoRequestDTO cig(String cig) {
    this.cig = cig;
    return this;
  }

   /**
   * Non gestito nella prima release - Identificativo univoco Gara-Lotto generato da ANAC. Alternativo all&#x27;idAppalto
   * @return cig
  **/
  @Schema(description = "Non gestito nella prima release - Identificativo univoco Gara-Lotto generato da ANAC. Alternativo all'idAppalto")
  public String getCig() {
    return cig;
  }

  public void setCig(String cig) {
    this.cig = cig;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresaCaricoRequestDTO presaCaricoRequestDTO = (PresaCaricoRequestDTO) o;
    return Objects.equals(this.idAppalto, presaCaricoRequestDTO.idAppalto) &&
        Objects.equals(this.cig, presaCaricoRequestDTO.cig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idAppalto, cig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresaCaricoRequestDTO {\n");
    
    sb.append("    idAppalto: ").append(toIndentedString(idAppalto)).append("\n");
    sb.append("    cig: ").append(toIndentedString(cig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
