/*
 * npa-gateway-ms API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.npaGateway;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CancellaAvvisoRequestDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:13:30.797833200+02:00[Europe/Berlin]")

public class CancellaAvvisoRequestDTO {
  @JsonProperty("idAppalto")
  private String idAppalto = null;

  @JsonProperty("idAvviso")
  private String idAvviso = null;

  @JsonProperty("motivo")
  private String motivo = null;

  public CancellaAvvisoRequestDTO idAppalto(String idAppalto) {
    this.idAppalto = idAppalto;
    return this;
  }

   /**
   * identificativo univoco dell&#x27;Appalto generato da ANAC.
   * @return idAppalto
  **/
  @Schema(required = true, description = "identificativo univoco dell'Appalto generato da ANAC.")
  public String getIdAppalto() {
    return idAppalto;
  }

  public void setIdAppalto(String idAppalto) {
    this.idAppalto = idAppalto;
  }

  public CancellaAvvisoRequestDTO idAvviso(String idAvviso) {
    this.idAvviso = idAvviso;
    return this;
  }

   /**
   * identificativo univoco dell&#x27;Avviso definito da ANAC. (A UUID specified by RFC4122)
   * @return idAvviso
  **/
  @Schema(required = true, description = "identificativo univoco dell'Avviso definito da ANAC. (A UUID specified by RFC4122)")
  public String getIdAvviso() {
    return idAvviso;
  }

  public void setIdAvviso(String idAvviso) {
    this.idAvviso = idAvviso;
  }

  public CancellaAvvisoRequestDTO motivo(String motivo) {
    this.motivo = motivo;
    return this;
  }

   /**
   * descrizione del motivo della richiesta di cancellazione
   * @return motivo
  **/
  @Schema(description = "descrizione del motivo della richiesta di cancellazione")
  public String getMotivo() {
    return motivo;
  }

  public void setMotivo(String motivo) {
    this.motivo = motivo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CancellaAvvisoRequestDTO cancellaAvvisoRequestDTO = (CancellaAvvisoRequestDTO) o;
    return Objects.equals(this.idAppalto, cancellaAvvisoRequestDTO.idAppalto) &&
        Objects.equals(this.idAvviso, cancellaAvvisoRequestDTO.idAvviso) &&
        Objects.equals(this.motivo, cancellaAvvisoRequestDTO.motivo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idAppalto, idAvviso, motivo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CancellaAvvisoRequestDTO {\n");
    
    sb.append("    idAppalto: ").append(toIndentedString(idAppalto)).append("\n");
    sb.append("    idAvviso: ").append(toIndentedString(idAvviso)).append("\n");
    sb.append("    motivo: ").append(toIndentedString(motivo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
