/*
 * npa-gateway-ms API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.npaGateway;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v102.npaGateway.AnagraficaOEType;
import it.appaltiecontratti.pcp.v102.npaGateway.AppaltoType;
import java.util.ArrayList;
import java.util.List;
/**
 * RichiestaAccessoFvoeRequestDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:13:30.797833200+02:00[Europe/Berlin]")

public class RichiestaAccessoFvoeRequestDTO {
  @JsonProperty("idRichiesta")
  private String idRichiesta = null;

  @JsonProperty("dataInizioAutorizzazione")
  private String dataInizioAutorizzazione = null;

  @JsonProperty("dataFineAutorizzazione")
  private String dataFineAutorizzazione = null;

  @JsonProperty("operatoriEconomici")
  private List<AnagraficaOEType> operatoriEconomici = new ArrayList<>();

  @JsonProperty("appalto")
  private AppaltoType appalto = null;

  @JsonProperty("richiedente")
  private AllOfRichiestaAccessoFvoeRequestDTORichiedente richiedente = null;

  public RichiestaAccessoFvoeRequestDTO idRichiesta(String idRichiesta) {
    this.idRichiesta = idRichiesta;
    return this;
  }

   /**
   * identificativo univoco della richiesta restituito da ANAC.
   * @return idRichiesta
  **/
  @Schema(description = "identificativo univoco della richiesta restituito da ANAC.")
  public String getIdRichiesta() {
    return idRichiesta;
  }

  public void setIdRichiesta(String idRichiesta) {
    this.idRichiesta = idRichiesta;
  }

  public RichiestaAccessoFvoeRequestDTO dataInizioAutorizzazione(String dataInizioAutorizzazione) {
    this.dataInizioAutorizzazione = dataInizioAutorizzazione;
    return this;
  }

   /**
   * data richiesta dal SA per accedere al Fascicolo (A datetime specified by ISO 8601 as profiled by RFC 3339)
   * @return dataInizioAutorizzazione
  **/
  @Schema(example = "2022-01-23T12:02:05Z", required = true, description = "data richiesta dal SA per accedere al Fascicolo (A datetime specified by ISO 8601 as profiled by RFC 3339)")
  public String getDataInizioAutorizzazione() {
    return dataInizioAutorizzazione;
  }

  public void setDataInizioAutorizzazione(String dataInizioAutorizzazione) {
    this.dataInizioAutorizzazione = dataInizioAutorizzazione;
  }

  public RichiestaAccessoFvoeRequestDTO dataFineAutorizzazione(String dataFineAutorizzazione) {
    this.dataFineAutorizzazione = dataFineAutorizzazione;
    return this;
  }

   /**
   * data richiesta dal SA come termine all&#x27; autorizzazione al Fascicolo (A datetime specified by ISO 8601 as profiled by RFC 3339)
   * @return dataFineAutorizzazione
  **/
  @Schema(example = "2022-01-23T12:02:05Z", description = "data richiesta dal SA come termine all' autorizzazione al Fascicolo (A datetime specified by ISO 8601 as profiled by RFC 3339)")
  public String getDataFineAutorizzazione() {
    return dataFineAutorizzazione;
  }

  public void setDataFineAutorizzazione(String dataFineAutorizzazione) {
    this.dataFineAutorizzazione = dataFineAutorizzazione;
  }

  public RichiestaAccessoFvoeRequestDTO operatoriEconomici(List<AnagraficaOEType> operatoriEconomici) {
    this.operatoriEconomici = operatoriEconomici;
    return this;
  }

  public RichiestaAccessoFvoeRequestDTO addOperatoriEconomiciItem(AnagraficaOEType operatoriEconomiciItem) {
    this.operatoriEconomici.add(operatoriEconomiciItem);
    return this;
  }

   /**
   * Oggetto specifico dell&#x27;anagrafica dell&#x27;OE
   * @return operatoriEconomici
  **/
  @Schema(required = true, description = "Oggetto specifico dell'anagrafica dell'OE")
  public List<AnagraficaOEType> getOperatoriEconomici() {
    return operatoriEconomici;
  }

  public void setOperatoriEconomici(List<AnagraficaOEType> operatoriEconomici) {
    this.operatoriEconomici = operatoriEconomici;
  }

  public RichiestaAccessoFvoeRequestDTO appalto(AppaltoType appalto) {
    this.appalto = appalto;
    return this;
  }

   /**
   * Get appalto
   * @return appalto
  **/
  @Schema(required = true, description = "")
  public AppaltoType getAppalto() {
    return appalto;
  }

  public void setAppalto(AppaltoType appalto) {
    this.appalto = appalto;
  }

  public RichiestaAccessoFvoeRequestDTO richiedente(AllOfRichiestaAccessoFvoeRequestDTORichiedente richiedente) {
    this.richiedente = richiedente;
    return this;
  }

   /**
   * Oggetto specifico dell&#x27;anagrafica dell&#x27;SA
   * @return richiedente
  **/
  @Schema(description = "Oggetto specifico dell'anagrafica dell'SA")
  public AllOfRichiestaAccessoFvoeRequestDTORichiedente getRichiedente() {
    return richiedente;
  }

  public void setRichiedente(AllOfRichiestaAccessoFvoeRequestDTORichiedente richiedente) {
    this.richiedente = richiedente;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RichiestaAccessoFvoeRequestDTO richiestaAccessoFvoeRequestDTO = (RichiestaAccessoFvoeRequestDTO) o;
    return Objects.equals(this.idRichiesta, richiestaAccessoFvoeRequestDTO.idRichiesta) &&
        Objects.equals(this.dataInizioAutorizzazione, richiestaAccessoFvoeRequestDTO.dataInizioAutorizzazione) &&
        Objects.equals(this.dataFineAutorizzazione, richiestaAccessoFvoeRequestDTO.dataFineAutorizzazione) &&
        Objects.equals(this.operatoriEconomici, richiestaAccessoFvoeRequestDTO.operatoriEconomici) &&
        Objects.equals(this.appalto, richiestaAccessoFvoeRequestDTO.appalto) &&
        Objects.equals(this.richiedente, richiestaAccessoFvoeRequestDTO.richiedente);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idRichiesta, dataInizioAutorizzazione, dataFineAutorizzazione, operatoriEconomici, appalto, richiedente);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RichiestaAccessoFvoeRequestDTO {\n");
    
    sb.append("    idRichiesta: ").append(toIndentedString(idRichiesta)).append("\n");
    sb.append("    dataInizioAutorizzazione: ").append(toIndentedString(dataInizioAutorizzazione)).append("\n");
    sb.append("    dataFineAutorizzazione: ").append(toIndentedString(dataFineAutorizzazione)).append("\n");
    sb.append("    operatoriEconomici: ").append(toIndentedString(operatoriEconomici)).append("\n");
    sb.append("    appalto: ").append(toIndentedString(appalto)).append("\n");
    sb.append("    richiedente: ").append(toIndentedString(richiedente)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
