/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione.AggiudicazioneCompletaType;
import it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione.EsitoProceduraAnnullataEnum;
import it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione.OfferteType;
import it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione.QuadroEconomicoType;
import java.math.BigDecimal;
import java.util.List;
/**
 * Oggetto che riporta i dati inerenti la fase di aggiudicazione sopra soglia e sotto soglia
 */
@Schema(description = "Oggetto che riporta i dati inerenti la fase di aggiudicazione sopra soglia e sotto soglia")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:12:50.940473900+02:00[Europe/Berlin]")

public class AggiudicazioneA133Type extends AggiudicazioneCompletaType {
  @JsonProperty("numeroOfferteAmmesse")
  private BigDecimal numeroOfferteAmmesse = null;

  @JsonProperty("esitoProceduraAnnullata")
  private EsitoProceduraAnnullataEnum esitoProceduraAnnullata = null;

  public AggiudicazioneA133Type numeroOfferteAmmesse(BigDecimal numeroOfferteAmmesse) {
    this.numeroOfferteAmmesse = numeroOfferteAmmesse;
    return this;
  }

   /**
   * numero di offerte ammesse
   * @return numeroOfferteAmmesse
  **/
  @Schema(required = true, description = "numero di offerte ammesse")
  public BigDecimal getNumeroOfferteAmmesse() {
    return numeroOfferteAmmesse;
  }

  public void setNumeroOfferteAmmesse(BigDecimal numeroOfferteAmmesse) {
    this.numeroOfferteAmmesse = numeroOfferteAmmesse;
  }

  public AggiudicazioneA133Type esitoProceduraAnnullata(EsitoProceduraAnnullataEnum esitoProceduraAnnullata) {
    this.esitoProceduraAnnullata = esitoProceduraAnnullata;
    return this;
  }

   /**
   * Get esitoProceduraAnnullata
   * @return esitoProceduraAnnullata
  **/
  @Schema(description = "")
  public EsitoProceduraAnnullataEnum getEsitoProceduraAnnullata() {
    return esitoProceduraAnnullata;
  }

  public void setEsitoProceduraAnnullata(EsitoProceduraAnnullataEnum esitoProceduraAnnullata) {
    this.esitoProceduraAnnullata = esitoProceduraAnnullata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggiudicazioneA133Type aggiudicazioneA133Type = (AggiudicazioneA133Type) o;
    return Objects.equals(this.numeroOfferteAmmesse, aggiudicazioneA133Type.numeroOfferteAmmesse) &&
        Objects.equals(this.esitoProceduraAnnullata, aggiudicazioneA133Type.esitoProceduraAnnullata) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroOfferteAmmesse, esitoProceduraAnnullata, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggiudicazioneA133Type {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    numeroOfferteAmmesse: ").append(toIndentedString(numeroOfferteAmmesse)).append("\n");
    sb.append("    esitoProceduraAnnullata: ").append(toIndentedString(esitoProceduraAnnullata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
