/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione.EsitoProceduraAnnullataEnum;
import it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione.OfferteType;
import java.util.ArrayList;
import java.util.List;
/**
 * Oggetto che riporta i dati inerenti la fase di aggiudicazione sopra soglia e sotto soglia
 */
@Schema(description = "Oggetto che riporta i dati inerenti la fase di aggiudicazione sopra soglia e sotto soglia")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:12:50.940473900+02:00[Europe/Berlin]")

public class AggiudicazioneA131Type {
  @JsonProperty("cig")
  private String cig = null;

  @JsonProperty("offertePresentate")
  private List<OfferteType> offertePresentate = new ArrayList<>();

  @JsonProperty("esitoProceduraAnnullata")
  private EsitoProceduraAnnullataEnum esitoProceduraAnnullata = null;

  public AggiudicazioneA131Type cig(String cig) {
    this.cig = cig;
    return this;
  }

   /**
   * codice identificativo lotto
   * @return cig
  **/
  @Schema(required = true, description = "codice identificativo lotto")
  public String getCig() {
    return cig;
  }

  public void setCig(String cig) {
    this.cig = cig;
  }

  public AggiudicazioneA131Type offertePresentate(List<OfferteType> offertePresentate) {
    this.offertePresentate = offertePresentate;
    return this;
  }

  public AggiudicazioneA131Type addOffertePresentateItem(OfferteType offertePresentateItem) {
    this.offertePresentate.add(offertePresentateItem);
    return this;
  }

   /**
   * Get offertePresentate
   * @return offertePresentate
  **/
  @Schema(required = true, description = "")
  public List<OfferteType> getOffertePresentate() {
    return offertePresentate;
  }

  public void setOffertePresentate(List<OfferteType> offertePresentate) {
    this.offertePresentate = offertePresentate;
  }

  public AggiudicazioneA131Type esitoProceduraAnnullata(EsitoProceduraAnnullataEnum esitoProceduraAnnullata) {
    this.esitoProceduraAnnullata = esitoProceduraAnnullata;
    return this;
  }

   /**
   * Get esitoProceduraAnnullata
   * @return esitoProceduraAnnullata
  **/
  @Schema(description = "")
  public EsitoProceduraAnnullataEnum getEsitoProceduraAnnullata() {
    return esitoProceduraAnnullata;
  }

  public void setEsitoProceduraAnnullata(EsitoProceduraAnnullataEnum esitoProceduraAnnullata) {
    this.esitoProceduraAnnullata = esitoProceduraAnnullata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggiudicazioneA131Type aggiudicazioneA131Type = (AggiudicazioneA131Type) o;
    return Objects.equals(this.cig, aggiudicazioneA131Type.cig) &&
        Objects.equals(this.offertePresentate, aggiudicazioneA131Type.offertePresentate) &&
        Objects.equals(this.esitoProceduraAnnullata, aggiudicazioneA131Type.esitoProceduraAnnullata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cig, offertePresentate, esitoProceduraAnnullata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggiudicazioneA131Type {\n");
    
    sb.append("    cig: ").append(toIndentedString(cig)).append("\n");
    sb.append("    offertePresentate: ").append(toIndentedString(offertePresentate)).append("\n");
    sb.append("    esitoProceduraAnnullata: ").append(toIndentedString(esitoProceduraAnnullata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
