/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
/**
* OneOfSchedaPostPubblicazioneTypeBody
*/
@JsonTypeInfo(
  use = JsonTypeInfo.Id.NAME,
  include = JsonTypeInfo.As.PROPERTY,
  property = "type")
@JsonSubTypes({
  @JsonSubTypes.Type(value = SchedaS1Type.class, name = "SchedaS1Type"),
  @JsonSubTypes.Type(value = SchedaS2Type.class, name = "SchedaS2Type"),
  @JsonSubTypes.Type(value = SchedaS3Type.class, name = "SchedaS3Type"),
  @JsonSubTypes.Type(value = SchedaS4Type.class, name = "SchedaS4Type"),
  @JsonSubTypes.Type(value = SchedaA129Type.class, name = "SchedaA129Type"),
  @JsonSubTypes.Type(value = SchedaA130Type.class, name = "SchedaA130Type"),
  @JsonSubTypes.Type(value = SchedaA131Type.class, name = "SchedaA131Type"),
  @JsonSubTypes.Type(value = SchedaA132Type.class, name = "SchedaA132Type"),
  @JsonSubTypes.Type(value = SchedaA133Type.class, name = "SchedaA133Type"),
  @JsonSubTypes.Type(value = SchedaA134Type.class, name = "SchedaA134Type"),
  @JsonSubTypes.Type(value = SchedaA135Type.class, name = "SchedaA135Type"),
  @JsonSubTypes.Type(value = SchedaA136Type.class, name = "SchedaA136Type"),
  @JsonSubTypes.Type(value = SchedaA137Type.class, name = "SchedaA137Type"),
  @JsonSubTypes.Type(value = SchedaA229Type.class, name = "SchedaA229Type"),
  @JsonSubTypes.Type(value = SchedaA230Type.class, name = "SchedaA230Type"),
  @JsonSubTypes.Type(value = SchedaA231Type.class, name = "SchedaA231Type"),
  @JsonSubTypes.Type(value = SchedaA232Type.class, name = "SchedaA232Type"),
  @JsonSubTypes.Type(value = SchedaA233Type.class, name = "SchedaA233Type"),
  @JsonSubTypes.Type(value = SchedaA234Type.class, name = "SchedaA234Type"),
  @JsonSubTypes.Type(value = SchedaA235Type.class, name = "SchedaA235Type"),
  @JsonSubTypes.Type(value = SchedaA236Type.class, name = "SchedaA236Type"),
  @JsonSubTypes.Type(value = SchedaA237Type.class, name = "SchedaA237Type"),
  @JsonSubTypes.Type(value = SchedaA31Type.class, name = "SchedaA31Type"),
  @JsonSubTypes.Type(value = SchedaA32Type.class, name = "SchedaA32Type"),
  @JsonSubTypes.Type(value = SchedaA33Type.class, name = "SchedaA33Type"),
  @JsonSubTypes.Type(value = SchedaA34Type.class, name = "SchedaA34Type"),
  @JsonSubTypes.Type(value = SchedaA35Type.class, name = "SchedaA35Type"),
  @JsonSubTypes.Type(value = SchedaA41Type.class, name = "SchedaA41Type"),
  @JsonSubTypes.Type(value = SchedaA42Type.class, name = "SchedaA42Type"),
  @JsonSubTypes.Type(value = SchedaA43Type.class, name = "SchedaA43Type"),
  @JsonSubTypes.Type(value = SchedaA44Type.class, name = "SchedaA44Type"),
  @JsonSubTypes.Type(value = SchedaA45Type.class, name = "SchedaA45Type"),
  @JsonSubTypes.Type(value = SchedaA46Type.class, name = "SchedaA46Type"),
  @JsonSubTypes.Type(value = SchedaA711Type.class, name = "SchedaA711Type"),
  @JsonSubTypes.Type(value = SchedaA712Type.class, name = "SchedaA712Type"),
  @JsonSubTypes.Type(value = SchedaNAGType.class, name = "SchedaNAGType"),
  @JsonSubTypes.Type(value = SchedaSC1Type.class, name = "SchedaSC1Type"),
  @JsonSubTypes.Type(value = SchedaI1Type.class, name = "SchedaI1Type"),
  @JsonSubTypes.Type(value = SchedaM1Type.class, name = "SchedaM1Type"),
  @JsonSubTypes.Type(value = SchedaM140Type.class, name = "SchedaM140Type"),
  @JsonSubTypes.Type(value = SchedaM2Type.class, name = "SchedaM2Type"),
  @JsonSubTypes.Type(value = SchedaM240Type.class, name = "SchedaM240Type"),
  @JsonSubTypes.Type(value = SchedaSA1Type.class, name = "SchedaSA1Type"),
  @JsonSubTypes.Type(value = SchedaRSU1Type.class, name = "SchedaRSU1Type"),
  @JsonSubTypes.Type(value = SchedaES1Type.class, name = "SchedaES1Type"),
  @JsonSubTypes.Type(value = SchedaCS1Type.class, name = "SchedaCS1Type"),
  @JsonSubTypes.Type(value = SchedaSO1Type.class, name = "SchedaSO1Type"),
  @JsonSubTypes.Type(value = SchedaSQ1Type.class, name = "SchedaSQ1Type"),
  @JsonSubTypes.Type(value = SchedaRI1Type.class, name = "SchedaRI1Type"),
  @JsonSubTypes.Type(value = SchedaAC1Type.class, name = "SchedaAC1Type"),
  @JsonSubTypes.Type(value = SchedaIR1Type.class, name = "SchedaIR1Type"),
  @JsonSubTypes.Type(value = SchedaCO1Type.class, name = "SchedaCO1Type"),
  @JsonSubTypes.Type(value = SchedaCO2Type.class, name = "SchedaCO2Type"),
  @JsonSubTypes.Type(value = SchedaCL1Type.class, name = "SchedaCL1Type"),
  @JsonSubTypes.Type(value = SchedaCM1Type.class, name = "SchedaCM1Type"),
  @JsonSubTypes.Type(value = SchedaCM2Type.class, name = "SchedaCM2Type"),
  @JsonSubTypes.Type(value = SchedaANNType.class, name = "SchedaANNType")
})
public interface OneOfSchedaPostPubblicazioneTypeBody {

}
