/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.2
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione.CodiceSchedaEnum;
import it.appaltiecontratti.pcp.v102.comunicaPostPubblicazione.StatoSchedaEnum;
import java.time.OffsetDateTime;
import java.util.UUID;
/**
 * Scheda generica definita dal contesto in cui si trova l&#x27;appalto
 */
@Schema(description = "Scheda generica definita dal contesto in cui si trova l'appalto")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-23T10:12:50.940473900+02:00[Europe/Berlin]")

public class SchedaType {
  @JsonProperty("_idScheda")
  private UUID _idScheda = null;

  @JsonProperty("codice")
  private CodiceSchedaEnum codice = null;

  @JsonProperty("versione")
  private String versione = null;

  @JsonProperty("_stato")
  private StatoSchedaEnum _stato = null;

  @JsonProperty("_dataCreazione")
  private java.time.OffsetDateTime _dataCreazione = null;

  public SchedaType _idScheda(UUID _idScheda) {
    this._idScheda = _idScheda;
    return this;
  }

   /**
   * Codice univoco della scheda. il campo viene determinato da anac e restituito nelle response. viene dunque ignorato il valore inserito nella post.
   * @return _idScheda
  **/
  @Schema(example = "f81d4fae-7dec-11d0-a765-00a0c91e6bf6", description = "Codice univoco della scheda. il campo viene determinato da anac e restituito nelle response. viene dunque ignorato il valore inserito nella post.")
  public UUID getIdScheda() {
    return _idScheda;
  }

  public void setIdScheda(UUID _idScheda) {
    this._idScheda = _idScheda;
  }

  public SchedaType codice(CodiceSchedaEnum codice) {
    this.codice = codice;
    return this;
  }

   /**
   * Get codice
   * @return codice
  **/
  @Schema(required = true, description = "")
  public CodiceSchedaEnum getCodice() {
    return codice;
  }

  public void setCodice(CodiceSchedaEnum codice) {
    this.codice = codice;
  }

  public SchedaType versione(String versione) {
    this.versione = versione;
    return this;
  }

   /**
   * versione della scheda. necessaria al motore interno ANAC.
   * @return versione
  **/
  @Schema(example = "1.0", required = true, description = "versione della scheda. necessaria al motore interno ANAC.")
  public String getVersione() {
    return versione;
  }

  public void setVersione(String versione) {
    this.versione = versione;
  }

  public SchedaType _stato(StatoSchedaEnum _stato) {
    this._stato = _stato;
    return this;
  }

   /**
   * Get _stato
   * @return _stato
  **/
  @Schema(description = "")
  public StatoSchedaEnum getStato() {
    return _stato;
  }

  public void setStato(StatoSchedaEnum _stato) {
    this._stato = _stato;
  }

  public SchedaType _dataCreazione(java.time.OffsetDateTime _dataCreazione) {
    this._dataCreazione = _dataCreazione;
    return this;
  }

   /**
   * data creazione della scheda (A date-time specified by ISO 8601 as profiled by RFC 3339)
   * @return _dataCreazione
  **/
  @Schema(example = "2022-01-23T12:02:05Z", description = "data creazione della scheda (A date-time specified by ISO 8601 as profiled by RFC 3339)")
  public java.time.OffsetDateTime getDataCreazione() {
    return _dataCreazione;
  }

  public void setDataCreazione(java.time.OffsetDateTime _dataCreazione) {
    this._dataCreazione = _dataCreazione;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchedaType schedaType = (SchedaType) o;
    return Objects.equals(this._idScheda, schedaType._idScheda) &&
        Objects.equals(this.codice, schedaType.codice) &&
        Objects.equals(this.versione, schedaType.versione) &&
        Objects.equals(this._stato, schedaType._stato) &&
        Objects.equals(this._dataCreazione, schedaType._dataCreazione);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_idScheda, codice, versione, _stato, _dataCreazione);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchedaType {\n");
    
    sb.append("    _idScheda: ").append(toIndentedString(_idScheda)).append("\n");
    sb.append("    codice: ").append(toIndentedString(codice)).append("\n");
    sb.append("    versione: ").append(toIndentedString(versione)).append("\n");
    sb.append("    _stato: ").append(toIndentedString(_stato)).append("\n");
    sb.append("    _dataCreazione: ").append(toIndentedString(_dataCreazione)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
