/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.4
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.serviziComuni;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.serviziComuni.DettaglioEsitoOperazioneEnum;
import it.appaltiecontratti.pcp.v1021.serviziComuni.ErroriEnum;
import it.appaltiecontratti.pcp.v1021.serviziComuni.EsitoEnum;
import it.appaltiecontratti.pcp.v1021.serviziComuni.TipoOperazioneEnum;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
/**
 * EsitoOperazioneType
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:36.947730900+02:00[Europe/Rome]")

public class EsitoOperazioneType {
  @JsonProperty("idAppalto")
  private UUID idAppalto = null;

  @JsonProperty("idPianificazione")
  private UUID idPianificazione = null;

  @JsonProperty("idScheda")
  private Object idScheda = null;

  @JsonProperty("codiceScheda")
  private String codiceScheda = null;

  @JsonProperty("idNuovaScheda")
  private Object idNuovaScheda = null;

  @JsonProperty("codiceNuovaScheda")
  private String codiceNuovaScheda = null;

  @JsonProperty("idAvviso")
  private UUID idAvviso = null;

  @JsonProperty("idNuovoAvviso")
  private UUID idNuovoAvviso = null;

  @JsonProperty("idContratto")
  private UUID idContratto = null;

  @JsonProperty("esito")
  private EsitoEnum esito = null;

  @JsonProperty("tipoOperazione")
  private TipoOperazioneEnum tipoOperazione = null;

  @JsonProperty("dettaglio")
  private DettaglioEsitoOperazioneEnum dettaglio = null;

  @JsonProperty("dataControllo")
  private OffsetDateTime dataControllo = null;

  @JsonProperty("errori")
  private List<ErroriEnum> errori = null;

  public EsitoOperazioneType idAppalto(UUID idAppalto) {
    this.idAppalto = idAppalto;
    return this;
  }

   /**
   * identificativo univoco dell&#x27;Appalto definito da ANAC. Restituito dall&#x27;operazione di creazione Appalto. (A UUID specified by RFC4122)
   * @return idAppalto
  **/
  @Schema(example = "f81d4fae-7dec-11d0-a765-00a0c91e6bf6", description = "identificativo univoco dell'Appalto definito da ANAC. Restituito dall'operazione di creazione Appalto. (A UUID specified by RFC4122)")
  public UUID getIdAppalto() {
    return idAppalto;
  }

  public void setIdAppalto(UUID idAppalto) {
    this.idAppalto = idAppalto;
  }

  public EsitoOperazioneType idPianificazione(UUID idPianificazione) {
    this.idPianificazione = idPianificazione;
    return this;
  }

   /**
   * identificativo univoco della Pianificazione definito da ANAC. Restituito dall&#x27;operazione di creazione Piano. (A UUID specified by RFC4122)
   * @return idPianificazione
  **/
  @Schema(example = "f81d4fae-7dec-11d0-a765-00a0c91e6bf6", description = "identificativo univoco della Pianificazione definito da ANAC. Restituito dall'operazione di creazione Piano. (A UUID specified by RFC4122)")
  public UUID getIdPianificazione() {
    return idPianificazione;
  }

  public void setIdPianificazione(UUID idPianificazione) {
    this.idPianificazione = idPianificazione;
  }

  public EsitoOperazioneType idScheda(Object idScheda) {
    this.idScheda = idScheda;
    return this;
  }

   /**
   * Identificativo univoco della Scheda definito da ANAC. (A UUID specified by RFC4122)
   * @return idScheda
  **/
  @Schema(description = "Identificativo univoco della Scheda definito da ANAC. (A UUID specified by RFC4122)")
  public Object getIdScheda() {
    return idScheda;
  }

  public void setIdScheda(Object idScheda) {
    this.idScheda = idScheda;
  }

  public EsitoOperazioneType codiceScheda(String codiceScheda) {
    this.codiceScheda = codiceScheda;
    return this;
  }

   /**
   * Codice della scheda con idScheda.
   * @return codiceScheda
  **/
  @Schema(description = "Codice della scheda con idScheda.")
  public String getCodiceScheda() {
    return codiceScheda;
  }

  public void setCodiceScheda(String codiceScheda) {
    this.codiceScheda = codiceScheda;
  }

  public EsitoOperazioneType idNuovaScheda(Object idNuovaScheda) {
    this.idNuovaScheda = idNuovaScheda;
    return this;
  }

   /**
   * Identificativo univoco della nuova Scheda definito da ANAC a seguito delle operazioni di modifica-avviso e rettifica-avviso. (A UUID specified by RFC4122)
   * @return idNuovaScheda
  **/
  @Schema(description = "Identificativo univoco della nuova Scheda definito da ANAC a seguito delle operazioni di modifica-avviso e rettifica-avviso. (A UUID specified by RFC4122)")
  public Object getIdNuovaScheda() {
    return idNuovaScheda;
  }

  public void setIdNuovaScheda(Object idNuovaScheda) {
    this.idNuovaScheda = idNuovaScheda;
  }

  public EsitoOperazioneType codiceNuovaScheda(String codiceNuovaScheda) {
    this.codiceNuovaScheda = codiceNuovaScheda;
    return this;
  }

   /**
   * Codice della scheda con idNuovaScheda.
   * @return codiceNuovaScheda
  **/
  @Schema(description = "Codice della scheda con idNuovaScheda.")
  public String getCodiceNuovaScheda() {
    return codiceNuovaScheda;
  }

  public void setCodiceNuovaScheda(String codiceNuovaScheda) {
    this.codiceNuovaScheda = codiceNuovaScheda;
  }

  public EsitoOperazioneType idAvviso(UUID idAvviso) {
    this.idAvviso = idAvviso;
    return this;
  }

   /**
   * identificativo univoco dell&#x27;Avviso generato da ANAC, qualora il tipo di scheda lo consente, durante l&#x27;invocazione delle operazioni dispositive conferma-piano, conferma-appalto, conferma-scheda.
   * @return idAvviso
  **/
  @Schema(description = "identificativo univoco dell'Avviso generato da ANAC, qualora il tipo di scheda lo consente, durante l'invocazione delle operazioni dispositive conferma-piano, conferma-appalto, conferma-scheda.")
  public UUID getIdAvviso() {
    return idAvviso;
  }

  public void setIdAvviso(UUID idAvviso) {
    this.idAvviso = idAvviso;
  }

  public EsitoOperazioneType idNuovoAvviso(UUID idNuovoAvviso) {
    this.idNuovoAvviso = idNuovoAvviso;
    return this;
  }

   /**
   * identificativo univoco del nuovo Avviso generato da ANAC a seguito delle operazioni di modifica-avviso e rettifica-avviso.
   * @return idNuovoAvviso
  **/
  @Schema(description = "identificativo univoco del nuovo Avviso generato da ANAC a seguito delle operazioni di modifica-avviso e rettifica-avviso.")
  public UUID getIdNuovoAvviso() {
    return idNuovoAvviso;
  }

  public void setIdNuovoAvviso(UUID idNuovoAvviso) {
    this.idNuovoAvviso = idNuovoAvviso;
  }

  public EsitoOperazioneType idContratto(UUID idContratto) {
    this.idContratto = idContratto;
    return this;
  }

   /**
   * identificativo univoco del Contratto generato da ANAC, qualora il tipo di scheda lo consente, durante l&#x27;invocazione dell&#x27; operazione dispositiva conferma-scheda.
   * @return idContratto
  **/
  @Schema(description = "identificativo univoco del Contratto generato da ANAC, qualora il tipo di scheda lo consente, durante l'invocazione dell' operazione dispositiva conferma-scheda.")
  public UUID getIdContratto() {
    return idContratto;
  }

  public void setIdContratto(UUID idContratto) {
    this.idContratto = idContratto;
  }

  public EsitoOperazioneType esito(EsitoEnum esito) {
    this.esito = esito;
    return this;
  }

   /**
   * Get esito
   * @return esito
  **/
  @Schema(description = "")
  public EsitoEnum getEsito() {
    return esito;
  }

  public void setEsito(EsitoEnum esito) {
    this.esito = esito;
  }

  public EsitoOperazioneType tipoOperazione(TipoOperazioneEnum tipoOperazione) {
    this.tipoOperazione = tipoOperazione;
    return this;
  }

   /**
   * Get tipoOperazione
   * @return tipoOperazione
  **/
  @Schema(description = "")
  public TipoOperazioneEnum getTipoOperazione() {
    return tipoOperazione;
  }

  public void setTipoOperazione(TipoOperazioneEnum tipoOperazione) {
    this.tipoOperazione = tipoOperazione;
  }

  public EsitoOperazioneType dettaglio(DettaglioEsitoOperazioneEnum dettaglio) {
    this.dettaglio = dettaglio;
    return this;
  }

   /**
   * Get dettaglio
   * @return dettaglio
  **/
  @Schema(description = "")
  public DettaglioEsitoOperazioneEnum getDettaglio() {
    return dettaglio;
  }

  public void setDettaglio(DettaglioEsitoOperazioneEnum dettaglio) {
    this.dettaglio = dettaglio;
  }

  public EsitoOperazioneType dataControllo(OffsetDateTime dataControllo) {
    this.dataControllo = dataControllo;
    return this;
  }

   /**
   * data in cui è stato effettuato il controllo dell&#x27;esito dell&#x27;operazione (A date-time specified by ISO 8601 as profiled by RFC 3339)
   * @return dataControllo
  **/
  @Schema(example = "2022-01-23T12:02:05Z", description = "data in cui è stato effettuato il controllo dell'esito dell'operazione (A date-time specified by ISO 8601 as profiled by RFC 3339)")
  public OffsetDateTime getDataControllo() {
    return dataControllo;
  }

  public void setDataControllo(OffsetDateTime dataControllo) {
    this.dataControllo = dataControllo;
  }

  public EsitoOperazioneType errori(List<ErroriEnum> errori) {
    this.errori = errori;
    return this;
  }

  public EsitoOperazioneType addErroriItem(ErroriEnum erroriItem) {
    if (this.errori == null) {
      this.errori = new ArrayList<>();
    }
    this.errori.add(erroriItem);
    return this;
  }

   /**
   * elenco degli errori
   * @return errori
  **/
  @Schema(description = "elenco degli errori")
  public List<ErroriEnum> getErrori() {
    return errori;
  }

  public void setErrori(List<ErroriEnum> errori) {
    this.errori = errori;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EsitoOperazioneType esitoOperazioneType = (EsitoOperazioneType) o;
    return Objects.equals(this.idAppalto, esitoOperazioneType.idAppalto) &&
        Objects.equals(this.idPianificazione, esitoOperazioneType.idPianificazione) &&
        Objects.equals(this.idScheda, esitoOperazioneType.idScheda) &&
        Objects.equals(this.codiceScheda, esitoOperazioneType.codiceScheda) &&
        Objects.equals(this.idNuovaScheda, esitoOperazioneType.idNuovaScheda) &&
        Objects.equals(this.codiceNuovaScheda, esitoOperazioneType.codiceNuovaScheda) &&
        Objects.equals(this.idAvviso, esitoOperazioneType.idAvviso) &&
        Objects.equals(this.idNuovoAvviso, esitoOperazioneType.idNuovoAvviso) &&
        Objects.equals(this.idContratto, esitoOperazioneType.idContratto) &&
        Objects.equals(this.esito, esitoOperazioneType.esito) &&
        Objects.equals(this.tipoOperazione, esitoOperazioneType.tipoOperazione) &&
        Objects.equals(this.dettaglio, esitoOperazioneType.dettaglio) &&
        Objects.equals(this.dataControllo, esitoOperazioneType.dataControllo) &&
        Objects.equals(this.errori, esitoOperazioneType.errori);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idAppalto, idPianificazione, idScheda, codiceScheda, idNuovaScheda, codiceNuovaScheda, idAvviso, idNuovoAvviso, idContratto, esito, tipoOperazione, dettaglio, dataControllo, errori);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EsitoOperazioneType {\n");
    
    sb.append("    idAppalto: ").append(toIndentedString(idAppalto)).append("\n");
    sb.append("    idPianificazione: ").append(toIndentedString(idPianificazione)).append("\n");
    sb.append("    idScheda: ").append(toIndentedString(idScheda)).append("\n");
    sb.append("    codiceScheda: ").append(toIndentedString(codiceScheda)).append("\n");
    sb.append("    idNuovaScheda: ").append(toIndentedString(idNuovaScheda)).append("\n");
    sb.append("    codiceNuovaScheda: ").append(toIndentedString(codiceNuovaScheda)).append("\n");
    sb.append("    idAvviso: ").append(toIndentedString(idAvviso)).append("\n");
    sb.append("    idNuovoAvviso: ").append(toIndentedString(idNuovoAvviso)).append("\n");
    sb.append("    idContratto: ").append(toIndentedString(idContratto)).append("\n");
    sb.append("    esito: ").append(toIndentedString(esito)).append("\n");
    sb.append("    tipoOperazione: ").append(toIndentedString(tipoOperazione)).append("\n");
    sb.append("    dettaglio: ").append(toIndentedString(dettaglio)).append("\n");
    sb.append("    dataControllo: ").append(toIndentedString(dataControllo)).append("\n");
    sb.append("    errori: ").append(toIndentedString(errori)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
