/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per il recupero delle tipologiche.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.codeList;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Oggetto generico di una tipologica
 */
@Schema(description = "Oggetto generico di una tipologica")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:37.409746500+02:00[Europe/Rome]")

public class TipologicaBaseType {
  @JsonProperty("idTipologica")
  private String idTipologica = null;

  @JsonProperty("descrizione")
  private Object descrizione = null;

  public TipologicaBaseType idTipologica(String idTipologica) {
    this.idTipologica = idTipologica;
    return this;
  }

   /**
   * Identificativo della tipologica utile per raggruppare i valori di ogni singola tipologica
   * @return idTipologica
  **/
  @Schema(example = "CPV", description = "Identificativo della tipologica utile per raggruppare i valori di ogni singola tipologica")
  public String getIdTipologica() {
    return idTipologica;
  }

  public void setIdTipologica(String idTipologica) {
    this.idTipologica = idTipologica;
  }

  public TipologicaBaseType descrizione(Object descrizione) {
    this.descrizione = descrizione;
    return this;
  }

   /**
   * Descrizione della tipologica.
   * @return descrizione
  **/
  @Schema(example = "cpv", description = "Descrizione della tipologica.")
  public Object getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(Object descrizione) {
    this.descrizione = descrizione;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TipologicaBaseType tipologicaBaseType = (TipologicaBaseType) o;
    return Objects.equals(this.idTipologica, tipologicaBaseType.idTipologica) &&
        Objects.equals(this.descrizione, tipologicaBaseType.descrizione);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idTipologica, descrizione);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TipologicaBaseType {\n");
    
    sb.append("    idTipologica: ").append(toIndentedString(idTipologica)).append("\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
