/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.AnacFormBaseType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.AppaltoP35Type;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.LottoP35Type;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.StazioneAppaltanteType;
import java.util.ArrayList;
import java.util.List;
/**
 * Contiene i dati relativi alla scelta del socio privato nella società mista.
 */
@Schema(description = "Contiene i dati relativi alla scelta del socio privato nella società mista.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:50.369647700+02:00[Europe/Rome]")

public class AnacFormP35Type extends AnacFormBaseType {
  @JsonProperty("appalto")
  private AppaltoP35Type appalto = null;

  @JsonProperty("lotti")
  private List<LottoP35Type> lotti = new ArrayList<>();

  public AnacFormP35Type appalto(AppaltoP35Type appalto) {
    this.appalto = appalto;
    return this;
  }

   /**
   * Get appalto
   * @return appalto
  **/
  @Schema(required = true, description = "")
  public AppaltoP35Type getAppalto() {
    return appalto;
  }

  public void setAppalto(AppaltoP35Type appalto) {
    this.appalto = appalto;
  }

  public AnacFormP35Type lotti(List<LottoP35Type> lotti) {
    this.lotti = lotti;
    return this;
  }

  public AnacFormP35Type addLottiItem(LottoP35Type lottiItem) {
    this.lotti.add(lottiItem);
    return this;
  }

   /**
   * Dati relativi ai lotti
   * @return lotti
  **/
  @Schema(required = true, description = "Dati relativi ai lotti")
  public List<LottoP35Type> getLotti() {
    return lotti;
  }

  public void setLotti(List<LottoP35Type> lotti) {
    this.lotti = lotti;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnacFormP35Type anacFormP35Type = (AnacFormP35Type) o;
    return Objects.equals(this.appalto, anacFormP35Type.appalto) &&
        Objects.equals(this.lotti, anacFormP35Type.lotti) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appalto, lotti, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnacFormP35Type {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    appalto: ").append(toIndentedString(appalto)).append("\n");
    sb.append("    lotti: ").append(toIndentedString(lotti)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
