/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.AppaltoAD127Type;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseAppaltoADType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseStrumentiProceduraAccordoQuadroSistemaDinamicoType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseSubappaltiType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.MotivoUrgenzaEnum;
/**
 * AppaltoAD227Type
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:50.369647700+02:00[Europe/Rome]")

public class AppaltoAD227Type extends AppaltoAD127Type {
  @JsonProperty("datiBase")
  private DatiBaseAppaltoADType datiBase = null;

  @JsonProperty("datiBaseProcedura")
  private AllOfAppaltoAD227TypeDatiBaseProcedura datiBaseProcedura = null;

  @JsonProperty("datiBaseStrumentiProcedura")
  private DatiBaseStrumentiProceduraAccordoQuadroSistemaDinamicoType datiBaseStrumentiProcedura = null;

  @JsonProperty("datiBaseSubappalti")
  private DatiBaseSubappaltiType datiBaseSubappalti = null;

  public AppaltoAD227Type datiBase(DatiBaseAppaltoADType datiBase) {
    this.datiBase = datiBase;
    return this;
  }

   /**
   * Get datiBase
   * @return datiBase
  **/
  @Schema(required = true, description = "")
  public DatiBaseAppaltoADType getDatiBase() {
    return datiBase;
  }

  public void setDatiBase(DatiBaseAppaltoADType datiBase) {
    this.datiBase = datiBase;
  }

  public AppaltoAD227Type datiBaseProcedura(AllOfAppaltoAD227TypeDatiBaseProcedura datiBaseProcedura) {
    this.datiBaseProcedura = datiBaseProcedura;
    return this;
  }

   /**
   * Get datiBaseProcedura
   * @return datiBaseProcedura
  **/
  @Schema(required = true, description = "")
  public AllOfAppaltoAD227TypeDatiBaseProcedura getDatiBaseProcedura() {
    return datiBaseProcedura;
  }

  public void setDatiBaseProcedura(AllOfAppaltoAD227TypeDatiBaseProcedura datiBaseProcedura) {
    this.datiBaseProcedura = datiBaseProcedura;
  }

  public AppaltoAD227Type datiBaseStrumentiProcedura(DatiBaseStrumentiProceduraAccordoQuadroSistemaDinamicoType datiBaseStrumentiProcedura) {
    this.datiBaseStrumentiProcedura = datiBaseStrumentiProcedura;
    return this;
  }

   /**
   * Get datiBaseStrumentiProcedura
   * @return datiBaseStrumentiProcedura
  **/
  @Schema(description = "")
  public DatiBaseStrumentiProceduraAccordoQuadroSistemaDinamicoType getDatiBaseStrumentiProcedura() {
    return datiBaseStrumentiProcedura;
  }

  public void setDatiBaseStrumentiProcedura(DatiBaseStrumentiProceduraAccordoQuadroSistemaDinamicoType datiBaseStrumentiProcedura) {
    this.datiBaseStrumentiProcedura = datiBaseStrumentiProcedura;
  }

  public AppaltoAD227Type datiBaseSubappalti(DatiBaseSubappaltiType datiBaseSubappalti) {
    this.datiBaseSubappalti = datiBaseSubappalti;
    return this;
  }

   /**
   * Get datiBaseSubappalti
   * @return datiBaseSubappalti
  **/
  @Schema(description = "")
  public DatiBaseSubappaltiType getDatiBaseSubappalti() {
    return datiBaseSubappalti;
  }

  public void setDatiBaseSubappalti(DatiBaseSubappaltiType datiBaseSubappalti) {
    this.datiBaseSubappalti = datiBaseSubappalti;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppaltoAD227Type appaltoAD227Type = (AppaltoAD227Type) o;
    return Objects.equals(this.datiBase, appaltoAD227Type.datiBase) &&
        Objects.equals(this.datiBaseProcedura, appaltoAD227Type.datiBaseProcedura) &&
        Objects.equals(this.datiBaseStrumentiProcedura, appaltoAD227Type.datiBaseStrumentiProcedura) &&
        Objects.equals(this.datiBaseSubappalti, appaltoAD227Type.datiBaseSubappalti) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datiBase, datiBaseProcedura, datiBaseStrumentiProcedura, datiBaseSubappalti, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppaltoAD227Type {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    datiBase: ").append(toIndentedString(datiBase)).append("\n");
    sb.append("    datiBaseProcedura: ").append(toIndentedString(datiBaseProcedura)).append("\n");
    sb.append("    datiBaseStrumentiProcedura: ").append(toIndentedString(datiBaseStrumentiProcedura)).append("\n");
    sb.append("    datiBaseSubappalti: ").append(toIndentedString(datiBaseSubappalti)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
