/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.AppaltoP13Type;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseStrumentiProceduraType1;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.MotivoUrgenzaEnum;
/**
 * AppaltoP213Type
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:50.369647700+02:00[Europe/Rome]")

public class AppaltoP213Type extends AppaltoP13Type {
  @JsonProperty("datiBase")
  private AllOfAppaltoP213TypeDatiBase datiBase = null;

  @JsonProperty("datiBaseProcedura")
  private AllOfAppaltoP213TypeDatiBaseProcedura datiBaseProcedura = null;

  @JsonProperty("datiBaseStrumentiProcedura")
  private DatiBaseStrumentiProceduraType1 datiBaseStrumentiProcedura = null;

  public AppaltoP213Type datiBase(AllOfAppaltoP213TypeDatiBase datiBase) {
    this.datiBase = datiBase;
    return this;
  }

   /**
   * Get datiBase
   * @return datiBase
  **/
  @Schema(required = true, description = "")
  public AllOfAppaltoP213TypeDatiBase getDatiBase() {
    return datiBase;
  }

  public void setDatiBase(AllOfAppaltoP213TypeDatiBase datiBase) {
    this.datiBase = datiBase;
  }

  public AppaltoP213Type datiBaseProcedura(AllOfAppaltoP213TypeDatiBaseProcedura datiBaseProcedura) {
    this.datiBaseProcedura = datiBaseProcedura;
    return this;
  }

   /**
   * Get datiBaseProcedura
   * @return datiBaseProcedura
  **/
  @Schema(required = true, description = "")
  public AllOfAppaltoP213TypeDatiBaseProcedura getDatiBaseProcedura() {
    return datiBaseProcedura;
  }

  public void setDatiBaseProcedura(AllOfAppaltoP213TypeDatiBaseProcedura datiBaseProcedura) {
    this.datiBaseProcedura = datiBaseProcedura;
  }

  public AppaltoP213Type datiBaseStrumentiProcedura(DatiBaseStrumentiProceduraType1 datiBaseStrumentiProcedura) {
    this.datiBaseStrumentiProcedura = datiBaseStrumentiProcedura;
    return this;
  }

   /**
   * Get datiBaseStrumentiProcedura
   * @return datiBaseStrumentiProcedura
  **/
  @Schema(description = "")
  public DatiBaseStrumentiProceduraType1 getDatiBaseStrumentiProcedura() {
    return datiBaseStrumentiProcedura;
  }

  public void setDatiBaseStrumentiProcedura(DatiBaseStrumentiProceduraType1 datiBaseStrumentiProcedura) {
    this.datiBaseStrumentiProcedura = datiBaseStrumentiProcedura;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppaltoP213Type appaltoP213Type = (AppaltoP213Type) o;
    return Objects.equals(this.datiBase, appaltoP213Type.datiBase) &&
        Objects.equals(this.datiBaseProcedura, appaltoP213Type.datiBaseProcedura) &&
        Objects.equals(this.datiBaseStrumentiProcedura, appaltoP213Type.datiBaseStrumentiProcedura) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datiBase, datiBaseProcedura, datiBaseStrumentiProcedura, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppaltoP213Type {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    datiBase: ").append(toIndentedString(datiBase)).append("\n");
    sb.append("    datiBaseProcedura: ").append(toIndentedString(datiBaseProcedura)).append("\n");
    sb.append("    datiBaseStrumentiProcedura: ").append(toIndentedString(datiBaseStrumentiProcedura)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
