/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.MultilinguaType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.OggettoContrattoEnum;
/**
 * Dato in comune con il Business Group Purpose delle eforms
 */
@Schema(description = "Dato in comune con il Business Group Purpose delle eforms")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:50.369647700+02:00[Europe/Rome]")

public class DatiBaseLottoPLType {
  @JsonProperty("oggettoContratto")
  private OggettoContrattoEnum oggettoContratto = null;

  @JsonProperty("oggetto")
  private String oggetto = null;

  @JsonProperty("oggettoMl")
  private MultilinguaType oggettoMl = null;

  public DatiBaseLottoPLType oggettoContratto(OggettoContrattoEnum oggettoContratto) {
    this.oggettoContratto = oggettoContratto;
    return this;
  }

   /**
   * Get oggettoContratto
   * @return oggettoContratto
  **/
  @Schema(required = true, description = "")
  public OggettoContrattoEnum getOggettoContratto() {
    return oggettoContratto;
  }

  public void setOggettoContratto(OggettoContrattoEnum oggettoContratto) {
    this.oggettoContratto = oggettoContratto;
  }

  public DatiBaseLottoPLType oggetto(String oggetto) {
    this.oggetto = oggetto;
    return this;
  }

   /**
   * Oggetto lotto - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-24 - Description del TED
   * @return oggetto
  **/
  @Schema(required = true, description = "Oggetto lotto - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-24 - Description del TED")
  public String getOggetto() {
    return oggetto;
  }

  public void setOggetto(String oggetto) {
    this.oggetto = oggetto;
  }

  public DatiBaseLottoPLType oggettoMl(MultilinguaType oggettoMl) {
    this.oggettoMl = oggettoMl;
    return this;
  }

   /**
   * Get oggettoMl
   * @return oggettoMl
  **/
  @Schema(description = "")
  public MultilinguaType getOggettoMl() {
    return oggettoMl;
  }

  public void setOggettoMl(MultilinguaType oggettoMl) {
    this.oggettoMl = oggettoMl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatiBaseLottoPLType datiBaseLottoPLType = (DatiBaseLottoPLType) o;
    return Objects.equals(this.oggettoContratto, datiBaseLottoPLType.oggettoContratto) &&
        Objects.equals(this.oggetto, datiBaseLottoPLType.oggetto) &&
        Objects.equals(this.oggettoMl, datiBaseLottoPLType.oggettoMl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oggettoContratto, oggetto, oggettoMl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatiBaseLottoPLType {\n");
    
    sb.append("    oggettoContratto: ").append(toIndentedString(oggettoContratto)).append("\n");
    sb.append("    oggetto: ").append(toIndentedString(oggetto)).append("\n");
    sb.append("    oggettoMl: ").append(toIndentedString(oggettoMl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
