/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * Dato in comune con il Business Group Contract delle eforms
 */
@Schema(description = "Dato in comune con il Business Group Contract delle eforms")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:50.369647700+02:00[Europe/Rome]")

public class DatiBaseAggiudicazioneAppaltoType {
  @JsonProperty("dataAggiudicazione")
  private OffsetDateTime dataAggiudicazione = null;

  public DatiBaseAggiudicazioneAppaltoType dataAggiudicazione(OffsetDateTime dataAggiudicazione) {
    this.dataAggiudicazione = dataAggiudicazione;
    return this;
  }

   /**
   * Data della decisione ufficiale di selezione dell&#x27;offerta vincitrice - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-1451 - Winner Decision Date del TED
   * @return dataAggiudicazione
  **/
  @Schema(required = true, description = "Data della decisione ufficiale di selezione dell'offerta vincitrice - nei casi in cui la scheda preveda un eform, corrisponde al campo bt-1451 - Winner Decision Date del TED")
  public OffsetDateTime getDataAggiudicazione() {
    return dataAggiudicazione;
  }

  public void setDataAggiudicazione(OffsetDateTime dataAggiudicazione) {
    this.dataAggiudicazione = dataAggiudicazione;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatiBaseAggiudicazioneAppaltoType datiBaseAggiudicazioneAppaltoType = (DatiBaseAggiudicazioneAppaltoType) o;
    return Objects.equals(this.dataAggiudicazione, datiBaseAggiudicazioneAppaltoType.dataAggiudicazione);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataAggiudicazione);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatiBaseAggiudicazioneAppaltoType {\n");
    
    sb.append("    dataAggiudicazione: ").append(toIndentedString(dataAggiudicazione)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
