/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.OggettoContrattoEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.StatoLottoEnum;
/**
 * Oggetto che riporta i dati del lotto
 */
@Schema(description = "Oggetto che riporta i dati del lotto")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:50.369647700+02:00[Europe/Rome]")

public class LottoType {
  @JsonProperty("cig")
  private String cig = null;

  @JsonProperty("lotIdentifier")
  private String lotIdentifier = null;

  @JsonProperty("oggetto")
  private String oggetto = null;

  @JsonProperty("importo")
  private String importo = null;

  @JsonProperty("stato")
  private StatoLottoEnum stato = null;

  @JsonProperty("oggettoContratto")
  private OggettoContrattoEnum oggettoContratto = null;

  public LottoType cig(String cig) {
    this.cig = cig;
    return this;
  }

   /**
   * codice identificativo lotto
   * @return cig
  **/
  @Schema(example = "9050626CD6", description = "codice identificativo lotto")
  public String getCig() {
    return cig;
  }

  public void setCig(String cig) {
    this.cig = cig;
  }

  public LottoType lotIdentifier(String lotIdentifier) {
    this.lotIdentifier = lotIdentifier;
    return this;
  }

   /**
   * Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED
   * @return lotIdentifier
  **/
  @Schema(description = "Id univoco del lotto generato dalla stazione appaltante - corrisponde al campo bt-137 - Purpose Lot Identifier del TED")
  public String getLotIdentifier() {
    return lotIdentifier;
  }

  public void setLotIdentifier(String lotIdentifier) {
    this.lotIdentifier = lotIdentifier;
  }

  public LottoType oggetto(String oggetto) {
    this.oggetto = oggetto;
    return this;
  }

   /**
   * descrizione del lotto
   * @return oggetto
  **/
  @Schema(example = "Servizio di assistenza e supporto specialistico per rilievo aereo ed elaborazione dati", description = "descrizione del lotto")
  public String getOggetto() {
    return oggetto;
  }

  public void setOggetto(String oggetto) {
    this.oggetto = oggetto;
  }

  public LottoType importo(String importo) {
    this.importo = importo;
    return this;
  }

   /**
   * Importo lotto in €
   * @return importo
  **/
  @Schema(description = "Importo lotto in €")
  public String getImporto() {
    return importo;
  }

  public void setImporto(String importo) {
    this.importo = importo;
  }

  public LottoType stato(StatoLottoEnum stato) {
    this.stato = stato;
    return this;
  }

   /**
   * Get stato
   * @return stato
  **/
  @Schema(description = "")
  public StatoLottoEnum getStato() {
    return stato;
  }

  public void setStato(StatoLottoEnum stato) {
    this.stato = stato;
  }

  public LottoType oggettoContratto(OggettoContrattoEnum oggettoContratto) {
    this.oggettoContratto = oggettoContratto;
    return this;
  }

   /**
   * Get oggettoContratto
   * @return oggettoContratto
  **/
  @Schema(description = "")
  public OggettoContrattoEnum getOggettoContratto() {
    return oggettoContratto;
  }

  public void setOggettoContratto(OggettoContrattoEnum oggettoContratto) {
    this.oggettoContratto = oggettoContratto;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LottoType lottoType = (LottoType) o;
    return Objects.equals(this.cig, lottoType.cig) &&
        Objects.equals(this.lotIdentifier, lottoType.lotIdentifier) &&
        Objects.equals(this.oggetto, lottoType.oggetto) &&
        Objects.equals(this.importo, lottoType.importo) &&
        Objects.equals(this.stato, lottoType.stato) &&
        Objects.equals(this.oggettoContratto, lottoType.oggettoContratto);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cig, lotIdentifier, oggetto, importo, stato, oggettoContratto);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LottoType {\n");
    
    sb.append("    cig: ").append(toIndentedString(cig)).append("\n");
    sb.append("    lotIdentifier: ").append(toIndentedString(lotIdentifier)).append("\n");
    sb.append("    oggetto: ").append(toIndentedString(oggetto)).append("\n");
    sb.append("    importo: ").append(toIndentedString(importo)).append("\n");
    sb.append("    stato: ").append(toIndentedString(stato)).append("\n");
    sb.append("    oggettoContratto: ").append(toIndentedString(oggettoContratto)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
