/*
 * Specifiche Servizi Appalto - OpenAPI 3.0
 * Sono descritte le Specifiche dei servizi esposti dalla Piattaforma Contratti Pubblici (PCP), richiamabili dalle Stazioni Appaltanti, per la gestione e la raccolta delle informazioni rilevanti nei processi che compongono l’intero ciclo di vita degli appalti.    #### Documentazione   La documentazione a supporto delle specifiche di interfaccia con i sistemi che interoperano con il nuovo sistema di digitalizzazione è redatta con il linguaggio di markup Markdown ed è presente al segunete url:     [documento-specifiche-servizi-npa](https://github.com/anticorruzione/npa/blob/main/docs/specifiche-interfacce/documento-specifiche-servizi-npa.md) ```
 *
 * OpenAPI spec version: 1.0.3
 * Contact: ufficio.uscp@anticorruzione.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.appaltiecontratti.pcp.v1021.comunicaAppalto;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.CategoriaEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.CategorieMerceologicheEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.CodIstatEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.CondizioniNegoziataEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.ContrattiDisposizioniParticolariEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseAccessibilitaType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseAggiudicazioneType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseAggiuntiviType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseCPVType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseComunicazioneType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseContrattoP7Type;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseDocumentiOptionalType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseLottoType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.DatiBaseTerminiInvioSoloOraType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.FinanziamentoType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.IpotesiCollegamentoType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.LottoP72BaseType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.ModalitaAcquisizioneEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.MotivoEsclusioneConcessioneEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.MotivoEsclusioneOrdinarioSpecialeEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.ParitaDiGenereGenerazionaleType;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.PrestazioniEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.TipoRealizzazioneContrattoEnum;
import it.appaltiecontratti.pcp.v1021.comunicaAppalto.TipologiaLavoroEnum;
import java.util.List;
/**
 * Oggetto che riporta i dati del lotto
 */
@Schema(description = "Oggetto che riporta i dati del lotto")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-25T10:09:50.369647700+02:00[Europe/Rome]")

public class LottoP72Type extends LottoP72BaseType {
  @JsonProperty("quadroEconomicoStandard")
  private AllOfLottoP72TypeQuadroEconomicoStandard quadroEconomicoStandard = null;

  @JsonProperty("datiBaseTerminiInvio")
  private DatiBaseTerminiInvioSoloOraType datiBaseTerminiInvio = null;

  public LottoP72Type quadroEconomicoStandard(AllOfLottoP72TypeQuadroEconomicoStandard quadroEconomicoStandard) {
    this.quadroEconomicoStandard = quadroEconomicoStandard;
    return this;
  }

   /**
   * Get quadroEconomicoStandard
   * @return quadroEconomicoStandard
  **/
  @Schema(description = "")
  public AllOfLottoP72TypeQuadroEconomicoStandard getQuadroEconomicoStandard() {
    return quadroEconomicoStandard;
  }

  public void setQuadroEconomicoStandard(AllOfLottoP72TypeQuadroEconomicoStandard quadroEconomicoStandard) {
    this.quadroEconomicoStandard = quadroEconomicoStandard;
  }

  public LottoP72Type datiBaseTerminiInvio(DatiBaseTerminiInvioSoloOraType datiBaseTerminiInvio) {
    this.datiBaseTerminiInvio = datiBaseTerminiInvio;
    return this;
  }

   /**
   * Get datiBaseTerminiInvio
   * @return datiBaseTerminiInvio
  **/
  @Schema(required = true, description = "")
  public DatiBaseTerminiInvioSoloOraType getDatiBaseTerminiInvio() {
    return datiBaseTerminiInvio;
  }

  public void setDatiBaseTerminiInvio(DatiBaseTerminiInvioSoloOraType datiBaseTerminiInvio) {
    this.datiBaseTerminiInvio = datiBaseTerminiInvio;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LottoP72Type lottoP72Type = (LottoP72Type) o;
    return Objects.equals(this.quadroEconomicoStandard, lottoP72Type.quadroEconomicoStandard) &&
        Objects.equals(this.datiBaseTerminiInvio, lottoP72Type.datiBaseTerminiInvio) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quadroEconomicoStandard, datiBaseTerminiInvio, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LottoP72Type {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    quadroEconomicoStandard: ").append(toIndentedString(quadroEconomicoStandard)).append("\n");
    sb.append("    datiBaseTerminiInvio: ").append(toIndentedString(datiBaseTerminiInvio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
